"""Grade 6 TEKS curriculum — monthly pacing guide for FISD Wortham Intermediate.

Standards sourced from Texas Education Agency (TEA) official TEKS documents:
  Math   §111.26  |  ELA §110.23  |  Science §112.18  |  Social Studies §113.18
School year: Aug 12, 2026 → May 28, 2027
"""

# ── Color scheme per subject ──────────────────────────────────────────────────
SUBJECT_STYLE = {
    "Math":           {"bg": "#eff6ff", "border": "#2563eb", "icon": "🔢", "tag_bg": "#dbeafe", "tag_color": "#1d4ed8"},
    "ELA":            {"bg": "#fdf4ff", "border": "#9333ea", "icon": "📖", "tag_bg": "#f3e8ff", "tag_color": "#7c3aed"},
    "Science":        {"bg": "#f0fdf4", "border": "#16a34a", "icon": "🔬", "tag_bg": "#dcfce7", "tag_color": "#15803d"},
    "Social Studies": {"bg": "#fff7ed", "border": "#ea580c", "icon": "🌍", "tag_bg": "#fed7aa", "tag_color": "#c2410c"},
}

# ── Monthly pacing: list of (month_label, [topics]) per subject ───────────────
# Ordered Aug → May (school year)
MONTHLY_PACING = {
    "Math": [
        ("Aug 12–Aug 31\nGetting Started", [
            "Review of 5th grade concepts",
            "Classify numbers: natural, whole, integer, rational",
            "Number line: ordering integers and rational numbers",
            "Absolute value and opposites",
            "Introduction to math tools & graphing calculator",
        ]),
        ("Sep\nRational Numbers & Operations", [
            "Multiply and divide integers",
            "Operations with fractions: multiply & divide",
            "Operations with decimals: multiply & divide",
            "Order of operations (PEMDAS) with rational numbers",
            "Real-world problems with rational numbers",
        ]),
        ("Oct\nRatios & Proportional Reasoning", [
            "Ratio concepts and notation (a:b, a/b, a to b)",
            "Unit rates and rate comparisons",
            "Equivalent ratios and ratio tables",
            "Proportional reasoning in real-world contexts",
            "Scale drawings and models",
            "⚠️ Fall Break: Oct 12–16",
        ]),
        ("Nov\nPercent", [
            "Percent as rate per 100",
            "Converting: fractions ↔ decimals ↔ percents",
            "Percent of a number (find the part, whole, or percent)",
            "Percent applications: tax, tip, discount, markup",
            "Simple interest introduction",
            "⚠️ Thanksgiving Break: Nov 23–27",
        ]),
        ("Dec\nExpressions & Variables", [
            "Independent vs. dependent quantities",
            "Writing algebraic expressions from words",
            "Evaluating expressions by substitution",
            "Equivalent expressions using properties",
            "Tables and graphs to represent relationships",
            "⚠️ Winter Break begins Dec 21",
        ]),
        ("Jan\nEquations & Inequalities", [
            "One-variable, one-step equations (all 4 operations)",
            "Solving equations using inverse operations",
            "Inequalities: writing, graphing on number line",
            "Real-world equation word problems",
            "⚠️ MLK Day: Jan 19",
        ]),
        ("Feb\nGeometry — Area & Surface Area", [
            "Area of triangles and quadrilaterals",
            "Area of composite figures",
            "Surface area of rectangular and triangular prisms",
            "Nets of 3-D figures",
            "⚠️ Presidents Day: Feb 15",
        ]),
        ("Mar\nGeometry — Volume & Coordinate Plane", [
            "Volume of rectangular prisms (fractional dimensions)",
            "Coordinate plane: all 4 quadrants",
            "Plotting ordered pairs (integers and fractions)",
            "Distance on coordinate plane (horizontal & vertical)",
            "Perimeter and area on coordinate plane",
            "⚠️ Spring Break: Mar 15–19",
        ]),
        ("Apr\nData Analysis & STAAR Prep", [
            "Statistical questions vs. non-statistical questions",
            "Mean, median, mode, range, IQR",
            "Dot plots and stem-and-leaf plots",
            "Box plots: quartiles, outliers",
            "Histograms: frequency tables",
            "Comparing data distributions",
            "★ STAAR Reading: ~Apr 6 | STAAR Math: ~Apr 8",
        ]),
        ("May\nFinancial Literacy & Review", [
            "Income: wages, salary, commission, tips",
            "Payroll deductions and income taxes (W-2 intro)",
            "Checking and savings accounts",
            "Credit scores and responsible credit use",
            "Year-end review and reinforcement",
            "⚠️ Last Day: May 28",
        ]),
    ],
    "ELA": [
        ("Aug 12–Aug 31\nGetting Started", [
            "Reading community building: routines, independent reading",
            "Literary elements review: plot, character, setting, theme, conflict",
            "Author's purpose: inform, entertain, persuade",
            "Writing process overview",
            "Grammar baseline: parts of speech review",
        ]),
        ("Sep\nNarrative Reading & Personal Writing", [
            "Point of view: first vs. third person",
            "Narrator's perspective and reliability",
            "Literary devices: simile, metaphor, imagery, hyperbole",
            "Personal narrative writing (small moment, sensory detail)",
            "Revising for voice and word choice",
            "Grammar: complete sentences, subject-verb agreement",
        ]),
        ("Oct\nInformational & Expository Texts", [
            "Main idea and key supporting details",
            "Text structures: cause/effect, compare/contrast, problem/solution",
            "Summarizing and paraphrasing non-fiction",
            "Informational essay writing (introduction, body, conclusion)",
            "Text features: headings, captions, diagrams",
            "Grammar: punctuation of complex sentences",
            "⚠️ Fall Break: Oct 12–16",
        ]),
        ("Nov\nResearch & Source Evaluation", [
            "Research process: topic selection, forming research questions",
            "Evaluating sources: credibility, relevance, accuracy",
            "Note-taking strategies: paraphrase vs. quote",
            "MLA citation basics (in-text citation and works cited)",
            "Avoiding plagiarism",
            "Research-based informational writing",
            "⚠️ Thanksgiving Break: Nov 23–27",
        ]),
        ("Dec\nArgumentative Texts & Writing Intro", [
            "Claims, reasons, and evidence in argument",
            "Counterclaims and rebuttals",
            "Evaluating an author's argument and logic",
            "Introduction to argumentative essay structure",
            "Vocabulary: connotation vs. denotation",
            "Grammar: conjunctions and transitions",
            "⚠️ Winter Break begins Dec 21",
        ]),
        ("Jan\nPoetry & Drama", [
            "Figurative language: personification, onomatopoeia, alliteration, allusion",
            "Poetic structure: stanza, line, rhyme scheme, free verse",
            "Analyzing mood and tone in poetry",
            "Drama elements: acts, scenes, stage directions, dialogue",
            "Comparing poem, drama, and prose versions of the same story",
            "⚠️ MLK Day: Jan 19",
        ]),
        ("Feb\nReading Comprehension & STAAR Focus", [
            "Making inferences from textual evidence",
            "Using context clues for unknown vocabulary",
            "Comparing multiple texts on the same topic",
            "Media literacy: analyzing visuals, charts, digital media",
            "Reading stamina: extended literary and informational passages",
            "Grammar: compound-complex sentences",
            "⚠️ Presidents Day: Feb 15",
        ]),
        ("Mar\nArgumentative Writing (Full Essay)", [
            "Developing a clear thesis/claim",
            "Integrating evidence with commentary (quote sandwich)",
            "Addressing counterclaims effectively",
            "Revision strategies: peer review, revision checklist",
            "Editing: grammar, spelling, comma rules",
            "⚠️ Spring Break: Mar 15–19",
        ]),
        ("Apr\nSTAAR Reading Preparation", [
            "STAAR format: paired literary + informational passages",
            "Cross-text synthesis questions",
            "Multiple-choice strategies: eliminating wrong answers",
            "Extended response (short constructed answer)",
            "Grammar review: verb tense, pronoun agreement, apostrophes",
            "★ STAAR Reading: ~Apr 6, 2027",
        ]),
        ("May\nIndependent Reading & Presentations", [
            "Student choice novel / independent reading project",
            "Book reviews and reader-response writing",
            "Oral presentations: organization, eye contact, voice",
            "Digital media project (optional)",
            "Portfolio reflection and goal-setting for Grade 7",
            "⚠️ Last Day: May 28",
        ]),
    ],
    "Science": [
        ("Aug 12–Aug 31\nLab Safety & Scientific Method", [
            "Lab safety rules, symbols, and equipment handling",
            "Scientific method: observation, hypothesis, experiment, analysis",
            "Independent vs. dependent variables; controlled variables",
            "SI units and metric conversions (length, mass, volume, temperature)",
            "Graphing: line graphs, bar graphs, scatter plots",
        ]),
        ("Sep\nMatter & Its Properties", [
            "Physical properties: mass, volume, density, melting/boiling point",
            "States of matter: solid, liquid, gas, plasma",
            "Phase changes: melting, freezing, evaporation, condensation, sublimation",
            "Mixtures vs. pure substances",
            "Elements, compounds, and mixtures",
        ]),
        ("Oct\nChemical & Physical Changes", [
            "Physical changes vs. chemical changes",
            "Evidence of chemical change (color change, gas production, precipitate, energy)",
            "Conservation of mass",
            "Common chemical reactions: combustion, oxidation (rust)",
            "⚠️ Fall Break: Oct 12–16",
        ]),
        ("Nov\nForce, Motion & Energy", [
            "Speed = distance ÷ time; velocity vs. speed",
            "Acceleration: change in speed or direction",
            "Newton's 1st Law: inertia",
            "Newton's 2nd Law: F = ma",
            "Newton's 3rd Law: action-reaction",
            "Balanced vs. unbalanced forces",
            "Simple machines: lever, pulley, inclined plane, wheel-and-axle",
            "⚠️ Thanksgiving Break: Nov 23–27",
        ]),
        ("Dec\nEarth's Structure & Plate Tectonics", [
            "Earth's layers: crust, mantle, outer core, inner core",
            "Continental drift theory: evidence (fossil records, fit of continents)",
            "Plate boundaries: divergent, convergent, transform",
            "Earthquakes: seismic waves, Richter scale, epicenter",
            "Volcanoes: hot spots, ring of fire, types of eruptions",
            "⚠️ Winter Break begins Dec 21",
        ]),
        ("Jan\nRock Cycle & Earth's Resources", [
            "Rock types: igneous, sedimentary, metamorphic — formation and examples",
            "Rock cycle: processes connecting rock types",
            "Weathering, erosion, and deposition",
            "Geologic time scale: eons, eras, periods",
            "Fossils: types, formation, relative vs. absolute dating",
            "Renewable vs. nonrenewable energy resources",
            "⚠️ MLK Day: Jan 19",
        ]),
        ("Feb\nOceans & Atmosphere", [
            "Ocean floor features: continental shelf, trench, mid-ocean ridge",
            "Ocean currents: surface and deep water (thermohaline)",
            "Tides: gravitational pull of moon",
            "Atmosphere layers: troposphere, stratosphere, mesosphere, thermosphere",
            "Weather vs. climate",
            "⚠️ Presidents Day: Feb 15",
        ]),
        ("Mar\nCells & Living Systems", [
            "Cell theory: three principles",
            "Cell organelles: nucleus, mitochondria, cell membrane, cell wall, chloroplast, vacuole",
            "Plant vs. animal cells: similarities and differences",
            "Cell processes: photosynthesis (intro), respiration (intro)",
            "Levels of organization: cell → tissue → organ → organ system → organism",
            "⚠️ Spring Break: Mar 15–19",
        ]),
        ("Apr\nEcosystems & STAAR Prep", [
            "Biotic vs. abiotic factors in an ecosystem",
            "Producers, consumers (primary/secondary/tertiary), decomposers",
            "Food chains and food webs — energy flow",
            "Energy pyramid: 10% rule",
            "Biogeochemical cycles: water cycle, carbon cycle, nitrogen cycle",
            "Population dynamics: limiting factors, carrying capacity",
            "★ Science benchmark assessment ~April",
        ]),
        ("May\nHuman Body & Year Review", [
            "Body systems overview: digestive, circulatory, respiratory, skeletal, muscular",
            "Body system interactions",
            "Human impact on ecosystems: pollution, habitat loss, invasive species",
            "Environmental stewardship and conservation",
            "Year-end review across all science units",
            "⚠️ Last Day: May 28",
        ]),
    ],
    "Social Studies": [
        ("Aug 12–Aug 31\nGeography Tools & Foundations", [
            "5 Themes of Geography: Location, Place, Human-Environment Interaction, Movement, Region",
            "Types of maps: physical, political, thematic, topographic",
            "Map elements: scale, legend, compass rose, latitude/longitude",
            "Time and chronology: BC/AD, BCE/CE; reading timelines",
            "Primary vs. secondary sources",
        ]),
        ("Sep\nMesopotamia & Ancient Near East", [
            "Tigris-Euphrates River Valley: geographic advantages",
            "Sumerians: first civilization, city-states, ziggurats, cuneiform writing",
            "Hammurabi's Code: rule of law and justice",
            "Babylonian, Assyrian, and Persian empires",
            "Cultural contributions: wheel, plow, number system (base-60)",
        ]),
        ("Oct\nAncient Egypt", [
            "Nile River: flooding, silt, and agriculture",
            "Social structure: pharaoh, priests, scribes, farmers, slaves",
            "Egyptian religion: polytheism, gods/goddesses, afterlife",
            "Mummification and the Book of the Dead",
            "Hieroglyphics, papyrus, and the Rosetta Stone",
            "Pyramids, sphinx, and monument architecture",
            "⚠️ Fall Break: Oct 12–16",
        ]),
        ("Nov\nAncient India & China", [
            "Indus Valley civilization: Harappa and Mohenjo-daro, urban planning",
            "Aryan migration and Vedic culture",
            "Hinduism: origins, Vedas, dharma, karma, caste system, reincarnation",
            "Buddhism: Siddhartha Gautama, Four Noble Truths, Eightfold Path",
            "Maurya Empire: Asoka's conversion and spread of Buddhism",
            "Yellow River (Huang He) civilization, Chinese dynasties: Shang, Zhou, Qin, Han",
            "Chinese inventions: paper, silk, gunpowder, compass",
            "Silk Road trade routes",
            "⚠️ Thanksgiving Break: Nov 23–27",
        ]),
        ("Dec\nWorld Religions Overview", [
            "Judaism: monotheism, Torah, Ten Commandments, covenant with God",
            "Christianity: Jesus of Nazareth, New Testament, spread through Roman Empire",
            "Islam: Muhammad, Quran, Five Pillars, spread across Middle East/Africa/Asia",
            "Hinduism & Buddhism (review and compare)",
            "Comparing world religions: origins, sacred texts, beliefs, practices",
            "Geographic distribution of world religions",
            "⚠️ Winter Break begins Dec 21",
        ]),
        ("Jan\nAncient Greece", [
            "Greek geography: peninsula, islands, city-states (polis)",
            "Athens vs. Sparta: government, culture, values",
            "Athenian democracy: citizens, assembly, direct democracy",
            "Persian Wars: Battle of Marathon, Thermopylae, Salamis",
            "Golden Age of Athens: Pericles, Parthenon, philosophy",
            "Greek philosophers: Socrates, Plato, Aristotle",
            "Alexander the Great and Hellenistic spread of Greek culture",
            "⚠️ MLK Day: Jan 19",
        ]),
        ("Feb\nAncient Rome", [
            "Roman geography: Italian peninsula, Mediterranean Sea advantages",
            "Roman Republic: Senate, consuls, patricians vs. plebeians",
            "Julius Caesar: rise and assassination",
            "Roman Empire: Augustus Caesar and Pax Romana",
            "Roman contributions: law (12 Tables), Latin language, aqueducts, roads",
            "Rise of Christianity within the Roman Empire",
            "Fall of Rome: internal conflict, barbarian invasions",
            "⚠️ Presidents Day: Feb 15",
        ]),
        ("Mar\nMedieval World & Byzantine Empire", [
            "Byzantine Empire: Eastern Roman Empire, Constantinople, Justinian Code",
            "Islamic Golden Age: advances in math, science, medicine, astronomy",
            "Medieval Europe: feudal system (king → lord → knight → serf)",
            "The Church in medieval life: monasteries, cathedrals, clergy",
            "The Crusades: causes, major events, effects on trade and culture",
            "Magna Carta: limits on royal power",
            "⚠️ Spring Break: Mar 15–19",
        ]),
        ("Apr\nExploration & Early Americas", [
            "Age of Exploration: motivations (God, Gold, Glory)",
            "Key explorers: Columbus, Vasco da Gama, Magellan",
            "Columbian Exchange: foods, plants, animals, diseases",
            "Early civilizations of the Americas: Maya, Aztec, Inca",
            "Spanish conquest and colonization impacts",
            "Document analysis: maps, treaties, primary sources",
        ]),
        ("May\nReview & Synthesis", [
            "Themes across civilizations: government, economy, culture, technology",
            "Comparing ancient and modern systems",
            "Current events connections to world history",
            "Social studies research project presentations",
            "Year-end review: geography, history, economics, culture",
            "⚠️ Last Day: May 28",
        ]),
    ],
}

# ── STAAR test subjects for Grade 6 ──────────────────────────────────────────
STAAR_INFO = {
    "Reading / ELA": {
        "estimated_date": "~April 6, 2027",
        "format": "Literary + Informational passages, multiple-choice + short written response",
        "key_readiness_standards": [
            "6.8 — Comprehension of literary text",
            "6.9 — Comprehension of informational text",
            "6.10 — Author's purpose and craft",
            "6.5 — Response skills (evidence-based answers)",
        ],
    },
    "Math": {
        "estimated_date": "~April 8, 2027",
        "format": "Multiple-choice + gridded response, calculator allowed for most sections",
        "key_readiness_standards": [
            "6.3 — Operations with integers and rational numbers",
            "6.4 — Proportionality (ratios, rates, percents)",
            "6.7 — Expressions, equations, inequalities",
            "6.8 — Geometry (area, volume)",
            "6.12 — Statistical measures and data representations",
        ],
    },
}

# ── Quick reference: subject → TEA standard code ─────────────────────────────
TEA_CODES = {
    "Math":           "§111.26 — Grade 6, Adopted 2012, Effective 2014",
    "ELA":            "§110.23 — Grade 6, Adopted 2017, Effective 2019",
    "Science":        "§112.18 — Grade 6, Adopted 2010 (revised 2018)",
    "Social Studies": "§113.18 — Grade 6, Adopted 2018",
}
