"""STAAR Prep data — resources, flashcards, mini-test questions for Grades 6-8.

Sources:
  Official tests  : tea.texas.gov / txpt.cambiumtds.com
  Khan Academy    : khanacademy.org (TX TEKS-aligned)
  Texas Gateway   : texasgateway.org
  Effortless Math : effortlessmath.com
  Quizlet / TXST  : flashcard sets
  Albert.io       : STAAR practice
"""

# ── Curated resource links by grade ──────────────────────────────────────────

RESOURCES = {
    6: {
        "Math": {
            "Official Practice Tests": [
                {"name": "Grade 6 Math — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-MA-2024-6&skipIntoTest=true&grade=6",
                 "note": "Official TEA online test · mirrors real STAAR format", "free": True},
                {"name": "2023 Grade 6 Math Practice Test PDF (TEA)",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2023-staar-redesign-6-math-practice-test.pdf",
                 "note": "Printable released practice test", "free": True},
                {"name": "TEA STAAR Released Test Questions Hub",
                 "url":  "https://tea.texas.gov/student-assessment/staar/staar-released-test-questions",
                 "note": "All released tests by grade and year", "free": True},
            ],
            "Khan Academy": [
                {"name": "Grade 6 Math — TX TEKS Aligned (Khan Academy)",
                 "url":  "https://www.khanacademy.org/math/grade-6-math-tx",
                 "note": "Video lessons + practice problems mapped to TEKS §111.26", "free": True},
            ],
            "Free Worksheets": [
                {"name": "Grade 6 STAAR Math Worksheets (Effortless Math)",
                 "url":  "https://www.effortlessmath.com/blog/grade-6-staar-math-worksheets/",
                 "note": "Strand-by-strand free worksheets", "free": True},
                {"name": "Free Grade 6 STAAR Math Practice Test (Effortless Math)",
                 "url":  "https://www.effortlessmath.com/math-topics/free-grade-6-staar-math-practice-test/",
                 "note": "Full practice test, no account needed", "free": True},
                {"name": "Grade 6 Math STAAR Worksheets (New Path Worksheets)",
                 "url":  "https://newpathworksheets.com/math/grade-6/texas-assessments-standards-staar",
                 "note": "Printable by TEKS standard", "free": True},
                {"name": "Texas Gateway — Grade 6 OER Math",
                 "url":  "https://texasgateway.org/book/grade-6-oer-math-edition-1",
                 "note": "Official OER textbook, free", "free": True},
            ],
            "Flashcards": [
                {"name": "Grade 6 Math STAAR Flashcards (Quizlet)",
                 "url":  "https://quizlet.com/206513731/6th-grade-math-staar-practice-flash-cards/",
                 "note": "Digital flashcards for key terms and concepts", "free": True},
                {"name": "Grade 6 Math TEKS Flashcards (TXST Mathworks)",
                 "url":  "https://www.txst.edu/mathworks/mathworks-curriculum/math-explorations-curriculum/online-learning-tools/staar-math-practice-questions/6th-grade-math-teks-online-flashcards.html",
                 "note": "Texas State University interactive flashcards", "free": True},
            ],
            "Practice Platforms": [
                {"name": "Albert.io — Grade 6 STAAR Math",
                 "url":  "https://www.albert.io/staar-grade-6-math",
                 "note": "Adaptive practice with explanations (free + paid tiers)", "free": False},
                {"name": "Union Test Prep — STAAR",
                 "url":  "https://uniontestprep.com/staar-test",
                 "note": "Free practice questions with explanations", "free": True},
                {"name": "MathHelp — Grade 6 STAAR Math",
                 "url":  "https://www.mathhelp.com/staar-math-test-prep/",
                 "note": "Video lessons + practice, free trial", "free": False},
            ],
        },
        "ELA / RLA": {
            "Official Practice Tests": [
                {"name": "Grade 6 RLA — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-ELA-Reading_2024-6&skipIntoTest=true&grade=6",
                 "note": "Official TEA online RLA test · real format", "free": True},
                {"name": "TEA STAAR Released Test Questions Hub",
                 "url":  "https://tea.texas.gov/student-assessment/staar/staar-released-test-questions",
                 "note": "All released RLA tests by grade and year", "free": True},
            ],
            "Khan Academy": [
                {"name": "Reading & Language Arts (Khan Academy)",
                 "url":  "https://www.khanacademy.org/ela/cc-6th-reading-vocab",
                 "note": "Grammar, vocabulary, reading comprehension practice", "free": True},
            ],
            "Free Worksheets": [
                {"name": "Texas Gateway — ELA Resources",
                 "url":  "https://texasgateway.org/",
                 "note": "Search 'Grade 6 ELA' for TEKS-aligned lessons", "free": True},
                {"name": "Albert.io — Grade 6 STAAR RLA",
                 "url":  "https://www.albert.io/staar-grade-6-rla",
                 "note": "Reading comprehension + grammar practice", "free": False},
            ],
            "Flashcards": [
                {"name": "Grade 6 ELA Literary Terms (Quizlet)",
                 "url":  "https://quizlet.com/subject/6th-grade-ela/",
                 "note": "Multiple sets for literary devices, grammar, vocabulary", "free": True},
            ],
        },
    },
    7: {
        "Math": {
            "Official Practice Tests": [
                {"name": "Grade 7 Math — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-MA-2024-7&skipIntoTest=true&grade=7",
                 "note": "Official TEA online test", "free": True},
                {"name": "2024 Grade 7 Math Answer Key (TEA)",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2024-staar-7-math-key.pdf",
                 "note": "Answer key for released test", "free": True},
                {"name": "TEA STAAR Released Test Questions Hub",
                 "url":  "https://tea.texas.gov/student-assessment/staar/staar-released-test-questions",
                 "note": "All released tests", "free": True},
            ],
            "Khan Academy": [
                {"name": "Grade 7 Math — TX TEKS Aligned (Khan Academy)",
                 "url":  "https://www.khanacademy.org/math/grade-7-math-tx",
                 "note": "Proportional relationships, expressions, geometry", "free": True},
            ],
            "Free Worksheets": [
                {"name": "Grade 7 STAAR Math Worksheets (Effortless Math)",
                 "url":  "https://www.effortlessmath.com/blog/staar-7-math-worksheets/",
                 "note": "Free strand-aligned worksheets", "free": True},
                {"name": "Free Grade 7 STAAR Math Practice Test",
                 "url":  "https://www.effortlessmath.com/math-topics/free-grade-7-staar-math-practice-test/",
                 "note": "Full free practice test", "free": True},
            ],
            "Practice Platforms": [
                {"name": "Albert.io — Grade 7 STAAR Math",
                 "url":  "https://www.albert.io/staar-grade-7-math",
                 "note": "Adaptive practice with rationale", "free": False},
                {"name": "MathHelp — Grade 7 STAAR Math",
                 "url":  "https://www.mathhelp.com/staar-grade-7-math-test-prep/",
                 "note": "Video lessons + practice", "free": False},
            ],
        },
        "ELA / RLA": {
            "Official Practice Tests": [
                {"name": "Grade 7 RLA — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-ELA-Reading_2024-7&skipIntoTest=true&grade=7",
                 "note": "Official TEA online RLA test", "free": True},
                {"name": "2024 Grade 7 RLA Answer Key (TEA)",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2024-staar-7-rla-key.pdf",
                 "note": "Answer key PDF", "free": True},
            ],
        },
    },
    8: {
        "Math": {
            "Official Practice Tests": [
                {"name": "Grade 8 Math — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-MA-2024-8&skipIntoTest=true&grade=8",
                 "note": "Official TEA online test", "free": True},
                {"name": "2023 Grade 8 Math Practice Test PDF",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2023-staar-redesign-8-math-practice-test.pdf",
                 "note": "Printable released test", "free": True},
                {"name": "2024 Grade 8 Math Answer Key",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2024-staar-8-math-key.pdf",
                 "note": "Answer key PDF", "free": True},
            ],
            "Khan Academy": [
                {"name": "Grade 8 Math — TX TEKS Aligned (Khan Academy)",
                 "url":  "https://www.khanacademy.org/math/grade-8-math-tx",
                 "note": "Linear equations, functions, geometry, statistics", "free": True},
            ],
            "Free Worksheets": [
                {"name": "Grade 8 STAAR Math Worksheets (Effortless Math)",
                 "url":  "https://www.effortlessmath.com/blog/staar-8-math-worksheets/",
                 "note": "Free strand-aligned worksheets", "free": True},
                {"name": "Free Grade 8 STAAR Math Practice Test",
                 "url":  "https://www.effortlessmath.com/math-topics/free-grade-8-staar-math-practice-test/",
                 "note": "Full free practice test", "free": True},
                {"name": "Grade 8 Math STAAR (New Path Worksheets)",
                 "url":  "https://newpathworksheets.com/math/grade-8/texas-assessments-standards-staar",
                 "note": "Printable by TEKS standard", "free": True},
            ],
            "Practice Platforms": [
                {"name": "Albert.io — Grade 8 STAAR Math",
                 "url":  "https://www.albert.io/staar-grade-8-math",
                 "note": "Adaptive practice with rationale", "free": False},
                {"name": "MathHelp — Grade 8 STAAR Math",
                 "url":  "https://www.mathhelp.com/staar-grade-8-math-test-prep/",
                 "note": "Video lessons + practice", "free": False},
            ],
        },
        "ELA / RLA": {
            "Official Practice Tests": [
                {"name": "Grade 8 RLA — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-ELA-Reading_2024-8&skipIntoTest=true&grade=8",
                 "note": "Official TEA online RLA test", "free": True},
                {"name": "2024 Grade 8 RLA Answer Key",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2024-staar-8-rla-key.pdf",
                 "note": "Answer key PDF", "free": True},
            ],
            "Practice Platforms": [
                {"name": "Albert.io — Grade 8 STAAR RLA",
                 "url":  "https://www.albert.io/staar-grade-8-rla",
                 "note": "Adaptive reading practice", "free": False},
            ],
        },
        "Science": {
            "Official Practice Tests": [
                {"name": "Grade 8 Science — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-SC-2024-8&skipIntoTest=true&grade=8",
                 "note": "Official TEA online science test", "free": True},
                {"name": "2023 Grade 8 Science Practice Test PDF",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2023-staar-redesign-8-science-practice-test.pdf",
                 "note": "Printable released test", "free": True},
                {"name": "2024 Grade 8 Science Practice Test Key",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2024-staar-8-science-practice-test-key.pdf",
                 "note": "Answer key PDF", "free": True},
            ],
            "Free Worksheets": [
                {"name": "Grade 8 Science STAAR (New Path Worksheets)",
                 "url":  "https://newpathworksheets.com/science/grade-8/texas-assessments-standards-staar",
                 "note": "Printable by TEKS standard", "free": True},
                {"name": "Albert.io — Grade 8 STAAR Science",
                 "url":  "https://www.albert.io/staar-grade-8-science",
                 "note": "Practice questions with explanations", "free": False},
            ],
        },
    },
}

# ── Flashcards — Grade 6 Math (aligned to TEKS §111.26) ─────────────────────

FLASHCARDS = {
    "Grade 6 Math": [
        # ── Number & Operations ───────────────────────────────────────────────
        {"q": "What is a rational number?",
         "a": "Any number that can be written as a fraction p/q where p and q are integers and q ≠ 0.\nIncludes: integers, fractions, terminating and repeating decimals.\nExamples: −3, ½, 0.75, −2.6̄",
         "strand": "Number & Operations"},
        {"q": "What is absolute value?",
         "a": "The distance of a number from 0 on a number line. Always ≥ 0.\n|−8| = 8   |5| = 5   |0| = 0",
         "strand": "Number & Operations"},
        {"q": "Rules for multiplying/dividing integers?",
         "a": "Same signs → Positive result\nDifferent signs → Negative result\n(−3) × (−4) = +12  |  (−3) × 4 = −12\n12 ÷ (−3) = −4  |  (−12) ÷ (−3) = +4",
         "strand": "Number & Operations"},
        {"q": "How do you add/subtract fractions with unlike denominators?",
         "a": "1. Find the Least Common Denominator (LCD)\n2. Rewrite each fraction with LCD\n3. Add/subtract numerators, keep denominator\n½ + ⅓ → LCD=6 → 3/6 + 2/6 = 5/6",
         "strand": "Number & Operations"},
        {"q": "How do you multiply fractions?",
         "a": "Multiply numerators × numerators, denominators × denominators. Simplify.\n¾ × ⅔ = (3×2)/(4×3) = 6/12 = ½",
         "strand": "Number & Operations"},
        {"q": "How do you divide fractions?",
         "a": "Keep the first fraction, Change ÷ to ×, Flip (reciprocal) the second fraction.\nKCF: ¾ ÷ ⅔ = ¾ × 3/2 = 9/8 = 1⅛",
         "strand": "Number & Operations"},
        {"q": "What is the Order of Operations (PEMDAS)?",
         "a": "Parentheses → Exponents → Multiply/Divide (left to right) → Add/Subtract (left to right)\n2 + 3 × 4 = 2 + 12 = 14  (NOT 20)",
         "strand": "Number & Operations"},
        # ── Proportionality ───────────────────────────────────────────────────
        {"q": "What is a ratio, and what are the 3 ways to write it?",
         "a": "A comparison of two quantities.\n3 ways: 3 to 4  |  3:4  |  3/4",
         "strand": "Proportionality"},
        {"q": "What is a unit rate?",
         "a": "A ratio with a denominator of 1, showing the rate per ONE unit.\n$2.50 per gallon  |  60 miles per hour\nDivide both parts by the denominator value.",
         "strand": "Proportionality"},
        {"q": "How do you find percent of a number?",
         "a": "Multiply the number by the percent written as a decimal.\n25% of 80 = 0.25 × 80 = 20\nOr: (percent/100) × whole = part",
         "strand": "Proportionality"},
        {"q": "How do you convert between fractions, decimals, and percents?",
         "a": "Fraction → Decimal: divide numerator by denominator (¾ = 0.75)\nDecimal → Percent: multiply by 100 (0.75 = 75%)\nPercent → Decimal: divide by 100 (35% = 0.35)\nPercent → Fraction: write over 100 and simplify (35% = 35/100 = 7/20)",
         "strand": "Proportionality"},
        {"q": "How do you calculate a discount/sale price?",
         "a": "Discount Amount = Original Price × Discount %\nSale Price = Original Price − Discount Amount\nExample: $60 shirt, 20% off → Discount = $12 → Sale Price = $48",
         "strand": "Proportionality"},
        {"q": "How do you calculate tax and tip?",
         "a": "Tax/Tip Amount = Original × Rate\nTotal = Original + Tax/Tip\nExample: $40 bill, 8% tax → Tax = $3.20 → Total = $43.20",
         "strand": "Proportionality"},
        # ── Expressions, Equations & Relationships ───────────────────────────
        {"q": "What is the difference between an expression and an equation?",
         "a": "Expression: no equal sign — just variables, numbers, operations (3x + 5)\nEquation: has an equal sign — states two things are equal (3x + 5 = 20)",
         "strand": "Expressions & Equations"},
        {"q": "What is the Distributive Property?",
         "a": "a(b + c) = ab + ac\nExamples:\n3(x + 4) = 3x + 12\n−2(5 − y) = −10 + 2y\nUse to expand or factor expressions.",
         "strand": "Expressions & Equations"},
        {"q": "How do you solve a one-step equation?",
         "a": "Use inverse operations to isolate the variable. Do the same to BOTH sides.\nx + 7 = 15 → subtract 7 → x = 8\nx − 4 = 9  → add 4 → x = 13\n3x = 21    → divide by 3 → x = 7\nx/5 = 4   → multiply by 5 → x = 20",
         "strand": "Expressions & Equations"},
        {"q": "What are independent and dependent variables?",
         "a": "Independent variable (x): the INPUT — you choose its value\nDependent variable (y): the OUTPUT — its value DEPENDS on x\nExample: hours worked (x) → money earned (y)",
         "strand": "Expressions & Equations"},
        {"q": "How do you write an inequality and graph it on a number line?",
         "a": "< less than (open circle, arrow left)\n> greater than (open circle, arrow right)\n≤ less than or equal (closed circle, arrow left)\n≥ greater than or equal (closed circle, arrow right)\nExample: x > 3 → open circle at 3, arrow pointing right",
         "strand": "Expressions & Equations"},
        # ── Geometry ─────────────────────────────────────────────────────────
        {"q": "Area formulas — triangle, parallelogram, trapezoid?",
         "a": "Triangle: A = ½ × base × height\nParallelogram: A = base × height\nTrapezoid: A = ½ × (b₁ + b₂) × height\nRemember: height must be PERPENDICULAR to the base",
         "strand": "Geometry"},
        {"q": "How do you find area of a composite figure?",
         "a": "Break it into familiar shapes (rectangles, triangles, etc.).\nAdd or subtract the areas of each piece.\nLabel each part carefully before calculating.",
         "strand": "Geometry"},
        {"q": "Volume of a rectangular prism?",
         "a": "V = length × width × height\nV = l × w × h\nUnits are CUBIC (cm³, in³, ft³)\nExample: 5 × 4 × 3 = 60 in³",
         "strand": "Geometry"},
        {"q": "How do you find surface area of a rectangular prism?",
         "a": "SA = 2(lw + lh + wh)\nOr draw the net: 6 rectangles, add up all 6 areas.\nUnits are SQUARE (cm², in²)",
         "strand": "Geometry"},
        {"q": "Coordinate plane: quadrants and plotting points?",
         "a": "Q1: (+, +) — right of y, above x\nQ2: (−, +) — left of y, above x\nQ3: (−, −) — left of y, below x\nQ4: (+, −) — right of y, below x\nPlot (x, y): move x units horizontally, then y units vertically",
         "strand": "Geometry"},
        # ── Data Analysis ─────────────────────────────────────────────────────
        {"q": "What are mean, median, mode, and range?",
         "a": "Mean: sum ÷ count (average)\nMedian: middle value when sorted (if even count, average the 2 middles)\nMode: most frequent value(s)\nRange: max − min\nData: 3, 7, 7, 9, 14 → Mean=8, Median=7, Mode=7, Range=11",
         "strand": "Data Analysis"},
        {"q": "What is the IQR and why does it matter?",
         "a": "IQR = Q3 − Q1 (Interquartile Range)\nMeasures the spread of the MIDDLE 50% of data.\nResistant to outliers (unlike range).\nQ1 = median of lower half | Q3 = median of upper half",
         "strand": "Data Analysis"},
        {"q": "What does a box plot show?",
         "a": "5-number summary:\n• Minimum (left whisker end)\n• Q1 (left edge of box)\n• Median (line inside box)\n• Q3 (right edge of box)\n• Maximum (right whisker end)\nBox width = IQR",
         "strand": "Data Analysis"},
        {"q": "Dot plot vs. histogram vs. stem-and-leaf — when to use each?",
         "a": "Dot plot: small data sets, see individual values, find clusters\nHistogram: large data sets grouped into intervals, see distribution shape\nStem-and-leaf: shows individual values AND distribution; good for comparing two data sets (back-to-back)",
         "strand": "Data Analysis"},
        {"q": "What is a statistical question?",
         "a": "A question that EXPECTS variability in the answers — different people would give different responses.\nStatistical: 'How many hours do 6th graders sleep per night?'\nNot statistical: 'How many hours did I sleep last night?'",
         "strand": "Data Analysis"},
        # ── Financial Literacy ────────────────────────────────────────────────
        {"q": "What is simple interest? Formula?",
         "a": "I = P × R × T\nI = Interest earned/paid\nP = Principal (starting amount)\nR = Annual interest Rate (as decimal)\nT = Time in years\nExample: $1,000 at 5% for 3 years → I = 1000 × 0.05 × 3 = $150",
         "strand": "Financial Literacy"},
        {"q": "Gross income vs. Net income?",
         "a": "Gross Income: total earnings BEFORE any deductions\nNet Income (Take-Home Pay): earnings AFTER taxes and deductions\nDeductions include: federal/state income tax, Social Security, Medicare, health insurance",
         "strand": "Financial Literacy"},
        {"q": "What is a credit score and why does it matter?",
         "a": "A number (300–850) measuring how reliably you repay borrowed money.\nHigher score → better loan rates, easier to rent/borrow\nAffected by: payment history, credit utilization, length of credit history, new accounts\n720+ = Good | 800+ = Excellent",
         "strand": "Financial Literacy"},
    ],
    "Grade 6 ELA": [
        # ── Literary Devices ──────────────────────────────────────────────────
        {"q": "Simile vs. Metaphor — what's the difference?",
         "a": "Simile: comparison using 'like' or 'as'\n  → 'She runs like the wind.'\nMetaphor: direct comparison WITHOUT 'like/as'\n  → 'He is a lion in battle.'",
         "strand": "Literary Devices"},
        {"q": "What is personification?",
         "a": "Giving human qualities, feelings, or actions to non-human things.\n→ 'The stars winked at us.'\n→ 'The storm roared and screamed all night.'",
         "strand": "Literary Devices"},
        {"q": "What is alliteration?",
         "a": "Repetition of the same consonant SOUND at the beginning of nearby words.\n→ 'Peter Piper picked a peck of pickled peppers.'\n→ 'Silly Sally swiftly shooed sheep.'",
         "strand": "Literary Devices"},
        {"q": "What is onomatopoeia?",
         "a": "Words that SOUND like what they describe.\n→ buzz, crash, sizzle, hiss, whoosh, bang\nUsed to make writing more vivid and sensory.",
         "strand": "Literary Devices"},
        {"q": "What is hyperbole?",
         "a": "An extreme exaggeration used for emphasis or humor (not meant literally).\n→ 'I've told you a million times!'\n→ 'I'm so hungry I could eat a horse.'",
         "strand": "Literary Devices"},
        {"q": "What is imagery?",
         "a": "Descriptive language that appeals to the 5 senses to create a mental picture.\nSight, Sound, Touch, Taste, Smell\n→ 'The warm, golden light filtered through the dusty curtains.'",
         "strand": "Literary Devices"},
        {"q": "What is foreshadowing?",
         "a": "Hints or clues in the text that suggest what will happen later in the story.\n→ Dark clouds gathering before a storm in the plot\n→ A character saying 'I have a bad feeling about this'\nCreates suspense and tension.",
         "strand": "Literary Devices"},
        {"q": "What is irony? Name the 3 types.",
         "a": "Verbal irony: saying the opposite of what you mean (sarcasm)\nSituational irony: the opposite of what's expected happens\nDramatic irony: the audience knows something the character doesn't",
         "strand": "Literary Devices"},
        # ── Reading / Comprehension ───────────────────────────────────────────
        {"q": "What are the 5 text structures? Give signal words for each.",
         "a": "1. Description: for example, specifically, such as\n2. Sequence/Chronological: first, next, then, finally\n3. Compare & Contrast: similarly, however, on the other hand, both\n4. Cause & Effect: because, therefore, as a result, so, since\n5. Problem & Solution: the problem is, one solution, as a result",
         "strand": "Comprehension"},
        {"q": "What is the author's purpose (PIE)?",
         "a": "P — Persuade: convince the reader of an opinion\nI — Inform: teach or explain facts/information\nE — Entertain: engage or amuse the reader\nMany texts have more than one purpose!",
         "strand": "Comprehension"},
        {"q": "What is a main idea vs. a supporting detail?",
         "a": "Main Idea: the most important point the author makes about the topic — the 'umbrella idea'\nSupporting Details: facts, examples, and explanations that back up the main idea\nTip: Ask 'What is this MOSTLY about?' → main idea",
         "strand": "Comprehension"},
        {"q": "How do you make an inference?",
         "a": "Inference = Text Evidence + Your Prior Knowledge\nYou read BETWEEN the lines — the author implies it but doesn't state it directly.\nAsk: What do I notice in the text? What do I already know? What can I conclude?",
         "strand": "Comprehension"},
        {"q": "What is point of view? Types?",
         "a": "1st Person: narrator IS a character — uses I, me, my, we\n3rd Person Limited: narrator tells one character's thoughts\n3rd Person Omniscient: narrator knows ALL characters' thoughts\n2nd Person: uses 'you' (rare in literature)",
         "strand": "Comprehension"},
        {"q": "What is theme vs. topic?",
         "a": "Topic: what the story is ABOUT (friendship, loyalty, courage)\nTheme: the MESSAGE or life lesson the author conveys about the topic\nTopic = 'courage' | Theme = 'True courage means acting even when you're afraid.'\nTheme is a COMPLETE SENTENCE with a lesson.",
         "strand": "Comprehension"},
        # ── Writing ───────────────────────────────────────────────────────────
        {"q": "What are the 3 types of writing tested on STAAR?",
         "a": "1. Narrative: tells a story (real or imagined), engages reader with plot/characters\n2. Informational/Explanatory: explains or teaches using facts\n3. Argumentative: makes a claim and supports it with evidence to persuade",
         "strand": "Writing"},
        {"q": "What is a thesis statement?",
         "a": "A sentence (usually at the end of the introduction) that states the main argument or central idea of an essay.\nStrong thesis: specific, debatable, answers 'so what?'\nWeak: 'I will discuss climate change.'\nStrong: 'Stricter recycling laws are essential to reducing plastic pollution in our oceans.'",
         "strand": "Writing"},
        {"q": "What is a counterclaim and why include it?",
         "a": "A counterclaim is the OPPOSING view to your argument.\nInclude it to show you understand multiple perspectives — then REFUTE it.\nStructure: 'Some may argue that ___. However, ___'\nShows sophisticated thinking and strengthens your argument.",
         "strand": "Writing"},
        {"q": "How do you integrate a quote into your writing?",
         "a": "Quote Sandwich:\n1. Introduce: Name the source or context\n2. Insert: Include the quote in quotation marks\n3. Explain: Tell the reader WHY this quote supports your point\n→ 'According to the article, \"...\" This shows that...'",
         "strand": "Writing"},
        # ── Grammar / Language ────────────────────────────────────────────────
        {"q": "What are the 8 parts of speech?",
         "a": "Noun (person, place, thing, idea)\nPronoun (replaces noun: he, she, they)\nVerb (action or state of being)\nAdjective (modifies noun)\nAdverb (modifies verb/adjective/adverb)\nPreposition (shows relationship: in, on, under)\nConjunction (connects: FANBOYS + AAAWWUBBIS)\nInterjection (expresses emotion: Wow! Oh!)",
         "strand": "Grammar"},
        {"q": "What is a complex sentence? How do you punctuate it?",
         "a": "Has one independent clause + one or more dependent clauses.\nDependent clause starts with subordinating conjunction (because, although, when, if, since...)\nIF dependent clause comes FIRST → use a comma after it\n→ 'Although it rained, we played outside.'\nIF independent clause comes first → NO comma\n→ 'We played outside although it rained.'",
         "strand": "Grammar"},
        {"q": "Connotation vs. Denotation?",
         "a": "Denotation: the literal, dictionary definition of a word\nConnotation: the emotional feeling or association a word carries\nExample: 'thin' vs. 'skinny' vs. 'slender'\n→ All mean the same thing (denotation), but have different feelings (connotation)",
         "strand": "Grammar"},
    ],
    "Grade 7 Math": [
        {"q": "What is a proportional relationship?",
         "a": "A relationship where two quantities increase/decrease at a constant rate (constant of proportionality k).\ny = kx — graph is a straight line through the ORIGIN\nk = y/x (unit rate)\nExample: $5.50 per pound → y = 5.5x",
         "strand": "Proportionality"},
        {"q": "How do you find percent increase or decrease?",
         "a": "% Change = (New − Old) / Old × 100\nIncrease: (New > Old) → positive %\nDecrease: (New < Old) → negative %\nExample: price goes from $80 to $100 → (100−80)/80 × 100 = 25% increase",
         "strand": "Proportionality"},
        {"q": "What is simple interest?",
         "a": "I = PRT\nP = Principal, R = Rate (decimal), T = Time (years)\nTotal Amount = P + I\nExample: $500 at 4% for 2 years → I = 500 × 0.04 × 2 = $40",
         "strand": "Financial Literacy"},
        {"q": "How do you solve two-step equations?",
         "a": "Work BACKWARDS using inverse operations — undo addition/subtraction first, then multiplication/division.\n2x + 5 = 17 → subtract 5 → 2x = 12 → divide by 2 → x = 6\nAlways check: 2(6) + 5 = 17 ✓",
         "strand": "Expressions & Equations"},
        {"q": "What is the circumference of a circle?",
         "a": "C = 2πr  or  C = πd\nr = radius, d = diameter, π ≈ 3.14159\nExample: circle with radius 5 → C = 2 × π × 5 ≈ 31.4 units",
         "strand": "Geometry"},
        {"q": "What is the area of a circle?",
         "a": "A = πr²\nr = radius (half the diameter)\nExample: circle with radius 4 → A = π × 4² = 16π ≈ 50.3 sq units",
         "strand": "Geometry"},
        {"q": "Supplementary vs. Complementary angles?",
         "a": "Complementary: two angles that add to 90°\nSupplementary: two angles that add to 180°\nMemory trick: C comes before S alphabetically, 90° comes before 180°",
         "strand": "Geometry"},
        {"q": "What are the measures of central tendency vs. variability?",
         "a": "Central tendency: Mean, Median, Mode (where is the CENTER?)\nVariability: Range, IQR, MAD (how SPREAD OUT is the data?)\nMAD (Mean Absolute Deviation) = average distance of each value from the mean",
         "strand": "Data Analysis"},
    ],
    "Grade 8 Math": [
        {"q": "What is slope and how do you calculate it?",
         "a": "Slope (m) = rise/run = (y₂ − y₁)/(x₂ − x₁)\nSlope tells how steep a line is and its direction.\nPositive slope: line goes up left to right\nNegative slope: line goes down left to right\nZero slope: horizontal line | Undefined: vertical line",
         "strand": "Proportionality"},
        {"q": "What is slope-intercept form?",
         "a": "y = mx + b\nm = slope (rate of change)\nb = y-intercept (where line crosses y-axis)\nExample: y = 2x + 3 → slope is 2, y-intercept is (0, 3)",
         "strand": "Proportionality"},
        {"q": "What is the Pythagorean Theorem?",
         "a": "a² + b² = c²\nFor right triangles: a and b are the LEGS, c is the HYPOTENUSE (longest side, opposite right angle)\nFind missing side: c = √(a² + b²)\nExample: legs 3 and 4 → c = √(9+16) = √25 = 5",
         "strand": "Geometry"},
        {"q": "What is scientific notation?",
         "a": "A way to write very large or small numbers.\nForm: a × 10ⁿ where 1 ≤ a < 10\n45,000 = 4.5 × 10⁴\n0.0032 = 3.2 × 10⁻³\nPositive exponent → large number\nNegative exponent → small number",
         "strand": "Number & Operations"},
        {"q": "What is a linear vs. non-linear function?",
         "a": "Linear: rate of change is CONSTANT → graph is a straight line → y = mx + b\nNon-linear: rate of change varies → graph is curved\nCheck: if the table shows equal changes in x but NOT equal changes in y → non-linear",
         "strand": "Expressions & Equations"},
        {"q": "How do you solve equations with variables on both sides?",
         "a": "1. Distribute if needed\n2. Combine like terms on each side\n3. Move all variables to one side (add/subtract)\n4. Solve for the variable\n5x + 3 = 2x + 12 → 3x = 9 → x = 3",
         "strand": "Expressions & Equations"},
        {"q": "Volume formulas: cylinder, cone, sphere?",
         "a": "Cylinder: V = πr²h\nCone: V = ⅓πr²h  (1/3 of cylinder)\nSphere: V = 4/3 πr³\nRemember: Cone = 1/3 Cylinder with same r and h",
         "strand": "Geometry"},
        {"q": "What is a transformation? Name the 4 types.",
         "a": "A change in position or size of a figure.\n1. Translation: slide (shift)\n2. Reflection: flip (mirror image)\n3. Rotation: turn around a point\n4. Dilation: resize (scale up or down)\nFirst 3 are rigid motions (preserve size/shape).",
         "strand": "Geometry"},
    ],
}

# ── Mini-test questions (STAAR-style MCQ) ────────────────────────────────────

MINI_TESTS = {
    "Grade 6 Math — Number & Operations": [
        {"q": "Which list shows the numbers in order from LEAST to GREATEST?",
         "opts": ["−3, 0, −½, ¼, 2", "−3, −½, 0, ¼, 2", "2, ¼, 0, −½, −3", "0, −½, −3, ¼, 2"],
         "ans": 1, "exp": "On a number line: −3 is furthest left, then −½, then 0, then ¼, then 2."},
        {"q": "What is the value of −24 ÷ (−6)?",
         "opts": ["−4", "−18", "4", "18"],
         "ans": 2, "exp": "Negative ÷ Negative = Positive. 24 ÷ 6 = 4."},
        {"q": "Which of the following is a rational number but NOT an integer?",
         "opts": ["−5", "0", "¾", "12"],
         "ans": 2, "exp": "Integers are whole numbers and their negatives. ¾ is a fraction — rational but not an integer."},
        {"q": "What is |−17| + |−8|?",
         "opts": ["−25", "−9", "9", "25"],
         "ans": 3, "exp": "|−17| = 17 and |−8| = 8. Their sum = 25."},
        {"q": "Evaluate: 3 + 4 × 2² − 6 ÷ 3",
         "opts": ["12", "17", "15", "11"],
         "ans": 2, "exp": "PEMDAS: 2²=4, then 4×4=16, then 6÷3=2, then 3+16−2 = 17."},
    ],
    "Grade 6 Math — Proportionality": [
        {"q": "A car travels 156 miles in 3 hours. What is the unit rate in miles per hour?",
         "opts": ["48 mph", "52 mph", "46.8 mph", "468 mph"],
         "ans": 1, "exp": "156 ÷ 3 = 52 miles per hour."},
        {"q": "A shirt originally costs $40. It is on sale for 25% off. What is the sale price?",
         "opts": ["$10", "$25", "$30", "$35"],
         "ans": 2, "exp": "Discount = 25% × $40 = $10. Sale price = $40 − $10 = $30."},
        {"q": "Which represents 35% written as a fraction in simplest form?",
         "opts": ["35/10", "7/20", "3/5", "7/2"],
         "ans": 1, "exp": "35% = 35/100. GCF of 35 and 100 is 5. 35/100 = 7/20."},
        {"q": "Juice boxes cost $6 for a pack of 8. What is the unit cost per juice box?",
         "opts": ["$0.65", "$0.75", "$0.80", "$1.33"],
         "ans": 1, "exp": "$6 ÷ 8 = $0.75 per juice box."},
        {"q": "A recipe uses 2½ cups of flour for every 36 cookies. How many cups are needed for 108 cookies?",
         "opts": ["5", "6½", "7½", "9"],
         "ans": 2, "exp": "108 ÷ 36 = 3. So 2½ × 3 = 7½ cups."},
    ],
    "Grade 6 Math — Expressions & Equations": [
        {"q": "Which expression represents 'eight less than twice a number n'?",
         "opts": ["8 − 2n", "2(8 − n)", "2n − 8", "2n + 8"],
         "ans": 2, "exp": "'Twice a number n' = 2n. 'Eight less than' means subtract 8 after: 2n − 8."},
        {"q": "Solve for x: 3x − 7 = 14",
         "opts": ["x = 2⅓", "x = 7", "x = 63", "x = −7"],
         "ans": 1, "exp": "Add 7 to both sides: 3x = 21. Divide by 3: x = 7."},
        {"q": "A plumber charges a $45 flat fee plus $30 per hour. Which equation gives total cost C for h hours?",
         "opts": ["C = 45h + 30", "C = 30h + 45", "C = 30 + 45h", "C = 75h"],
         "ans": 1, "exp": "Fixed cost = $45 (flat fee). Variable cost = $30 × h. Total: C = 30h + 45."},
        {"q": "Which value of x makes the inequality x − 4 > 9 true?",
         "opts": ["x = 10", "x = 12", "x = 13", "x = 14"],
         "ans": 3, "exp": "x − 4 > 9 → x > 13. So x = 14 is the only option greater than 13."},
        {"q": "Simplify: 4(2x + 3) − 5x",
         "opts": ["8x + 3", "3x + 12", "3x + 3", "8x + 12"],
         "ans": 1, "exp": "Distribute: 8x + 12. Subtract 5x: 3x + 12."},
    ],
    "Grade 6 Math — Geometry": [
        {"q": "A triangle has a base of 12 cm and a height of 9 cm. What is its area?",
         "opts": ["108 cm²", "54 cm²", "21 cm²", "42 cm²"],
         "ans": 1, "exp": "A = ½ × b × h = ½ × 12 × 9 = 54 cm²."},
        {"q": "A rectangular prism has length = 6 ft, width = 4 ft, and height = 5 ft. What is its volume?",
         "opts": ["120 ft³", "148 ft²", "74 ft³", "60 ft³"],
         "ans": 0, "exp": "V = l × w × h = 6 × 4 × 5 = 120 ft³."},
        {"q": "Point A is at (−3, 2) and Point B is at (4, 2). What is the distance between them?",
         "opts": ["1 unit", "5 units", "6 units", "7 units"],
         "ans": 3, "exp": "Same y-coordinate → horizontal distance = |4 − (−3)| = |7| = 7 units."},
        {"q": "What is the area of a trapezoid with bases of 8 in and 12 in, and a height of 5 in?",
         "opts": ["50 in²", "100 in²", "40 in²", "60 in²"],
         "ans": 0, "exp": "A = ½(b₁ + b₂)h = ½(8 + 12)(5) = ½(20)(5) = 50 in²."},
        {"q": "A point is plotted at (−4, −3). In which quadrant is it located?",
         "opts": ["Quadrant I", "Quadrant II", "Quadrant III", "Quadrant IV"],
         "ans": 2, "exp": "Both coordinates are negative → Quadrant III (−, −)."},
    ],
    "Grade 6 Math — Data Analysis": [
        {"q": "Ages: 11, 13, 12, 14, 12, 11, 15. What is the median?",
         "opts": ["11", "12", "13", "12.5"],
         "ans": 1, "exp": "Sorted: 11, 11, 12, 12, 13, 14, 15. Middle (4th) value = 12."},
        {"q": "Data: 2, 5, 7, 9, 11, 14, 18. What is the IQR?",
         "opts": ["16", "9", "7", "11"],
         "ans": 1, "exp": "Q1 = 5 (median of 2,5,7), Q3 = 14 (median of 11,14,18). IQR = 14 − 5 = 9."},
        {"q": "Scores: 72, 85, 91, 85, 78, 95, 85. What is the mode?",
         "opts": ["85", "84.4", "85.5", "78"],
         "ans": 0, "exp": "85 appears 3 times — more than any other value."},
        {"q": "A box plot has Q1=15, Median=22, Q3=30, Min=8, Max=45. What is the IQR?",
         "opts": ["37", "22", "15", "8"],
         "ans": 2, "exp": "IQR = Q3 − Q1 = 30 − 15 = 15."},
        {"q": "Which data display is BEST for showing the frequency of values in intervals?",
         "opts": ["Dot plot", "Stem-and-leaf", "Histogram", "Box plot"],
         "ans": 2, "exp": "Histograms group data into intervals and show how many fall in each — perfect for frequency by interval."},
    ],
    "Grade 6 ELA — Literary Devices": [
        {"q": "Which sentence uses a SIMILE?",
         "opts": ['"The classroom was a zoo."',
                  '"Her smile was sunshine."',
                  '"He ran like a cheetah through the halls."',
                  '"The hungry book devoured her attention."'],
         "ans": 2, "exp": "'Like a cheetah' uses 'like' to compare — that's a simile. The others are metaphors or personification."},
        {"q": "What literary device is used in: 'The thunder grumbled and the wind whispered warnings'?",
         "opts": ["Simile", "Personification", "Alliteration", "Hyperbole"],
         "ans": 1, "exp": "Thunder 'grumbling' and wind 'whispering' gives human actions to non-human things = personification."},
        {"q": "Which is an example of HYPERBOLE?",
         "opts": ['"The cat sat quietly."',
                  '"I am so tired I could sleep for a year."',
                  '"The stars looked like diamonds."',
                  '"She arrived early every morning."'],
         "ans": 1, "exp": "'Sleep for a year' is an extreme exaggeration for emphasis — that's hyperbole."},
        {"q": "'Buzz,' 'crash,' and 'sizzle' are all examples of:",
         "opts": ["Alliteration", "Personification", "Onomatopoeia", "Imagery"],
         "ans": 2, "exp": "These words imitate sounds — that's onomatopoeia."},
        {"q": "Which sentence contains alliteration?",
         "opts": ['"She sells seashells by the seashore."',
                  '"The moon is a silver coin."',
                  '"I have told you a thousand times!"',
                  '"The door creaked open slowly."'],
         "ans": 0, "exp": "Repeated 's' sound at the start of words = alliteration."},
    ],
    "Grade 6 ELA — Reading Comprehension": [
        {"q": "Which text structure signal words indicate CAUSE AND EFFECT?",
         "opts": ["First, next, then, finally",
                  "Because, therefore, as a result",
                  "Similarly, however, on the other hand",
                  "For example, specifically, such as"],
         "ans": 1, "exp": "'Because,' 'therefore,' and 'as a result' signal that one event caused another = cause and effect."},
        {"q": "An author's purpose to PERSUADE means:",
         "opts": ["The author wants to teach the reader facts",
                  "The author wants to entertain with a story",
                  "The author wants to convince the reader to agree with an opinion",
                  "The author wants to describe a process step by step"],
         "ans": 2, "exp": "Persuade = convince the reader to take a position or action (PIE: Persuade, Inform, Entertain)."},
        {"q": "Making an INFERENCE requires:",
         "opts": ["Only information directly stated in the text",
                  "Only the reader's personal opinion",
                  "Text evidence combined with prior knowledge",
                  "The author's stated conclusion"],
         "ans": 2, "exp": "Inference = reading between the lines: text clues + what you already know = logical conclusion."},
        {"q": "The THEME of a story is best described as:",
         "opts": ["A one-word topic like 'friendship'",
                  "A summary of all the plot events",
                  "A life lesson or message expressed as a complete sentence",
                  "The main character's goal in the story"],
         "ans": 2, "exp": "Theme is a universal message (complete sentence). Topic = friendship. Theme = 'True friendship requires sacrifice.'"},
        {"q": "In a text using COMPARE AND CONTRAST structure, which signal word would you expect?",
         "opts": ["Therefore", "As a result", "However", "Finally"],
         "ans": 2, "exp": "'However' signals a contrast. Compare/contrast texts highlight similarities AND differences between subjects."},
        {"q": "Which point of view uses the pronouns 'I,' 'me,' and 'my'?",
         "opts": ["Third person omniscient", "Third person limited", "Second person", "First person"],
         "ans": 3, "exp": "First person narration: the narrator is a character and uses I/me/my. The reader only knows what that character knows."},
        {"q": "A student reads: 'Maria slammed her book shut and stared at the ceiling.' What can be inferred?",
         "opts": ["Maria is happy about what she read", "Maria is frustrated or upset", "Maria finished her homework",
                  "Maria is looking for something on the ceiling"],
         "ans": 1, "exp": "Slamming a book shut and staring at the ceiling are signs of frustration — we infer this from the text evidence."},
        {"q": "Which is the MAIN IDEA of a paragraph that talks about causes of deforestation, loss of habitat, and endangered species?",
         "opts": ["Trees are cut down every day in rainforests",
                  "Deforestation harms the environment in multiple ways",
                  "Animals lose their homes when trees are removed",
                  "Endangered species need protection from hunters"],
         "ans": 1, "exp": "The 'umbrella' idea covering all details is that deforestation causes environmental harm. The other choices are supporting details."},
        {"q": "What does 'context clues' mean?",
         "opts": ["Looking up a word in the dictionary", "Asking a teacher what a word means",
                  "Using surrounding words and sentences to figure out an unknown word's meaning",
                  "Breaking a word into prefix, root, and suffix"],
         "ans": 2, "exp": "Context clues are hints in the surrounding text that help you determine the meaning of an unfamiliar word without a dictionary."},
    ],
}

# ── Extended question bank — 15+ fresh questions per strand ──────────────────
# Combined with MINI_TESTS base (5 each) this gives 20+ per strand.
# Use get_question_pool() to get the deduplicated full pool.

MINI_TEST_EXTRA = {
    "Grade 6 Math — Number & Operations": [
        {"q": "What is the GCF of 24 and 36?",
         "opts": ["4", "6", "12", "18"],
         "ans": 2, "exp": "Factors of 24: 1,2,3,4,6,8,12,24. Factors of 36: 1,2,3,4,6,9,12,18,36. GCF = 12."},
        {"q": "Simplify: ¾ + ⅔",
         "opts": ["5/6", "1 5/12", "7/12", "1½"],
         "ans": 1, "exp": "LCD = 12. ¾ = 9/12, ⅔ = 8/12. Sum = 17/12 = 1 5/12."},
        {"q": "What is the LCM of 4 and 6?",
         "opts": ["2", "12", "24", "10"],
         "ans": 1, "exp": "Multiples of 4: 4,8,12… Multiples of 6: 6,12… LCM = 12."},
        {"q": "What is −7 + (−5)?",
         "opts": ["2", "−2", "12", "−12"],
         "ans": 3, "exp": "Negative + Negative: add the values and keep the sign. 7 + 5 = 12 → −12."},
        {"q": "Which is an example of an irrational number?",
         "opts": ["¾", "−4", "√25", "√7"],
         "ans": 3, "exp": "√7 ≈ 2.6457… never repeats or terminates → irrational. √25 = 5 is rational."},
        {"q": "Evaluate: 2 + 3 × (8 − 5)²",
         "opts": ["29", "125", "47", "65"],
         "ans": 0, "exp": "PEMDAS: (8−5)=3, 3²=9, 3×9=27, 2+27 = 29."},
        {"q": "Which list is in order from GREATEST to LEAST?",
         "opts": ["0.5, ¾, 1¼", "1¼, ¾, 0.5", "¾, 1¼, 0.5", "0.5, 1¼, ¾"],
         "ans": 1, "exp": "Convert: 1¼=1.25, ¾=0.75, 0.5. Greatest to least: 1.25 > 0.75 > 0.5."},
        {"q": "What is 3.6 × 0.4?",
         "opts": ["1.44", "14.4", "0.144", "144"],
         "ans": 0, "exp": "36 × 4 = 144. Two decimal places total → 1.44."},
        {"q": "Which is equivalent to (−3)²?",
         "opts": ["−9", "9", "−6", "6"],
         "ans": 1, "exp": "(−3)² = (−3) × (−3) = +9. Both negatives cancel → positive."},
        {"q": "A number is 4 less than |−11|. What is the number?",
         "opts": ["7", "−7", "15", "−15"],
         "ans": 0, "exp": "|−11| = 11. Four less: 11 − 4 = 7."},
        {"q": "What is the LCM of 6 and 8?",
         "opts": ["2", "14", "24", "48"],
         "ans": 2, "exp": "Multiples of 6: 6,12,18,24. Multiples of 8: 8,16,24. LCM = 24."},
        {"q": "Which correctly shows the Commutative Property of Multiplication?",
         "opts": ["5 × (3 × 2) = (5 × 3) × 2", "5 × 0 = 0", "5 × 3 = 3 × 5", "5 × 1 = 5"],
         "ans": 2, "exp": "Commutative Property: a × b = b × a. Order of factors can change without changing the product."},
        {"q": "Simplify: ⅔ ÷ ⅚",
         "opts": ["4/5", "5/9", "9/10", "5/4"],
         "ans": 0, "exp": "Keep-Change-Flip: ⅔ × 6/5 = 12/15 = 4/5."},
        {"q": "The temperature was −8°F. It rose 15°F. What is the new temperature?",
         "opts": ["7°F", "−7°F", "23°F", "−23°F"],
         "ans": 0, "exp": "−8 + 15 = 7°F. |15| > |−8| so the result is positive."},
        {"q": "Which expression has a value of −3?",
         "opts": ["(−15) ÷ (−5)", "15 ÷ (−5)", "(−15) ÷ 5 × (−1)", "5 − 15 + 7"],
         "ans": 1, "exp": "15 ÷ (−5) = −3. Positive ÷ Negative = Negative."},
        {"q": "Which of the following is a perfect square?",
         "opts": ["20", "50", "49", "75"],
         "ans": 2, "exp": "49 = 7 × 7. A perfect square is the product of an integer multiplied by itself."},
    ],
    "Grade 6 Math — Proportionality": [
        {"q": "If 5 notebooks cost $12.50, how much do 8 notebooks cost?",
         "opts": ["$18.00", "$20.00", "$16.50", "$22.50"],
         "ans": 1, "exp": "Unit rate = $12.50 ÷ 5 = $2.50 each. 8 × $2.50 = $20.00."},
        {"q": "A store marks up a $30 item by 40%. What is the selling price?",
         "opts": ["$40", "$42", "$38", "$12"],
         "ans": 1, "exp": "Markup = 40% × $30 = $12. Selling price = $30 + $12 = $42."},
        {"q": "Convert 0.625 to a fraction in simplest form.",
         "opts": ["625/1000", "5/8", "6/10", "3/5"],
         "ans": 1, "exp": "0.625 = 625/1000. GCF = 125. 625/1000 = 5/8."},
        {"q": "A car gets 32 miles per gallon. How far can it travel on 5.5 gallons?",
         "opts": ["160 mi", "176 mi", "180 mi", "164 mi"],
         "ans": 1, "exp": "32 × 5.5 = 176 miles."},
        {"q": "Which table shows a proportional relationship?",
         "opts": ["x:1,2,3 → y:3,6,10", "x:1,2,3 → y:4,8,12", "x:1,2,3 → y:2,5,7", "x:1,2,3 → y:1,3,6"],
         "ans": 1, "exp": "y/x must be constant: 4/1=4, 8/2=4, 12/3=4 ✓. Constant ratio = proportional."},
        {"q": "A scale drawing uses 1 cm = 25 m. A building is 6.4 cm on the drawing. Actual length?",
         "opts": ["160 m", "3.9 m", "320 m", "64 m"],
         "ans": 0, "exp": "6.4 × 25 = 160 m."},
        {"q": "What percent is 18 of 72?",
         "opts": ["18%", "20%", "25%", "40%"],
         "ans": 2, "exp": "18/72 = 0.25 = 25%."},
        {"q": "An item costs $45 after a 10% discount. What was the original price?",
         "opts": ["$49.50", "$50", "$55", "$40.50"],
         "ans": 1, "exp": "90% of original = $45. Original = 45 ÷ 0.90 = $50."},
        {"q": "Miguel drove 210 miles in 3.5 hours. How long to drive 360 miles at the same rate?",
         "opts": ["5 hours", "6 hours", "5.5 hours", "4.8 hours"],
         "ans": 1, "exp": "Rate = 210/3.5 = 60 mph. Time = 360/60 = 6 hours."},
        {"q": "A bag has 8 red and 12 blue marbles. What fraction are red?",
         "opts": ["8/12", "2/5", "3/5", "⅜"],
         "ans": 1, "exp": "Total = 20. Red fraction = 8/20 = 2/5."},
        {"q": "Convert 3/8 to a percent.",
         "opts": ["37.5%", "38%", "0.375%", "83%"],
         "ans": 0, "exp": "3 ÷ 8 = 0.375. Multiply by 100 → 37.5%."},
        {"q": "A worker earns $126 in 9 hours. How much for 12 hours?",
         "opts": ["$152", "$162", "$168", "$180"],
         "ans": 2, "exp": "Rate = $126 ÷ 9 = $14/hr. 14 × 12 = $168."},
        {"q": "An item is 40% off its $80 original price. What is the sale price?",
         "opts": ["$32", "$40", "$48", "$56"],
         "ans": 2, "exp": "Discount = 40% × $80 = $32. Sale price = $80 − $32 = $48."},
        {"q": "45% of 240 students take math club. How many is that?",
         "opts": ["100", "108", "120", "45"],
         "ans": 1, "exp": "0.45 × 240 = 108 students."},
        {"q": "4 pounds of apples cost $6.20. Cost per pound?",
         "opts": ["$1.45", "$1.50", "$1.55", "$1.60"],
         "ans": 2, "exp": "$6.20 ÷ 4 = $1.55 per pound."},
        {"q": "Which ratio is equivalent to 6:10?",
         "opts": ["2:5", "3:5", "6:15", "12:15"],
         "ans": 1, "exp": "6:10 simplifies to 3:5 (divide both by 2). Equivalent ratios keep the same value."},
    ],
    "Grade 6 Math — Expressions & Equations": [
        {"q": "Which is equivalent to 5(x − 3)?",
         "opts": ["5x − 3", "5x − 15", "5x + 15", "x − 15"],
         "ans": 1, "exp": "Distribute 5: 5×x = 5x, 5×(−3) = −15. Result: 5x − 15."},
        {"q": "Solve: x/4 + 3 = 7",
         "opts": ["x = 1", "x = 16", "x = 10", "x = 28"],
         "ans": 1, "exp": "Subtract 3: x/4 = 4. Multiply by 4: x = 16. Check: 16/4 + 3 = 7 ✓"},
        {"q": "Bike rental: $5/hr plus $8 flat fee. Equation for total cost C?",
         "opts": ["C = 8h + 5", "C = 5h + 8", "C = 13h", "C = 5 + 8"],
         "ans": 1, "exp": "Variable cost = 5h. Fixed cost = 8. Total: C = 5h + 8."},
        {"q": "What is 5x − 2y when x = 3 and y = 4?",
         "opts": ["7", "23", "14", "8"],
         "ans": 0, "exp": "5(3) − 2(4) = 15 − 8 = 7."},
        {"q": "Identify the constant in the expression 4n + 7.",
         "opts": ["4", "n", "7", "4n"],
         "ans": 2, "exp": "A constant is a number with no variable. In 4n + 7, the constant is 7."},
        {"q": "Which shows the Commutative Property of Addition?",
         "opts": ["3 + (4+5) = (3+4) + 5", "3 + 4 = 4 + 3", "3(4+5) = 12+15", "3 + 0 = 3"],
         "ans": 1, "exp": "Commutative: a + b = b + a. Changing order doesn't change the sum."},
        {"q": "Solve: 3x + 6 = 21",
         "opts": ["x = 5", "x = 9", "x = 15", "x = 3"],
         "ans": 0, "exp": "Subtract 6: 3x = 15. Divide by 3: x = 5. Check: 3(5)+6 = 21 ✓"},
        {"q": "A tank has 80 gallons draining at 4 gal/min. After how many minutes are 20 gallons left?",
         "opts": ["15 min", "20 min", "25 min", "10 min"],
         "ans": 0, "exp": "80 − 4m = 20 → 4m = 60 → m = 15 minutes."},
        {"q": "Which expression means 'five more than twice a number x'?",
         "opts": ["5x + 2", "2x + 5", "2(x + 5)", "5(x + 2)"],
         "ans": 1, "exp": "'Twice a number x' = 2x. 'Five more than' adds 5: 2x + 5."},
        {"q": "Which graph shows x ≥ −2?",
         "opts": ["Open circle at −2, arrow left", "Closed circle at −2, arrow right",
                  "Open circle at −2, arrow right", "Closed circle at −2, arrow left"],
         "ans": 1, "exp": "≥ uses a CLOSED circle (includes −2). Arrow goes RIGHT (values larger than −2)."},
        {"q": "Simplify: 3(x + 4) + 2(x − 1)",
         "opts": ["5x + 10", "5x + 14", "5x + 11", "6x + 10"],
         "ans": 0, "exp": "Distribute: 3x+12+2x−2. Combine: 5x + 10."},
        {"q": "n ÷ 3 < 5. Which value of n makes this true?",
         "opts": ["n = 15", "n = 18", "n = 12", "n = 21"],
         "ans": 2, "exp": "n < 15. Only n = 12 is less than 15."},
        {"q": "y is always 3 more than x. Which equation is correct?",
         "opts": ["y = 3x", "y = x + 3", "y = 3 − x", "y = x/3"],
         "ans": 1, "exp": "'3 more than x' means add 3: y = x + 3."},
        {"q": "Evaluate: 5(3 − 1)² − 4",
         "opts": ["16", "36", "20", "6"],
         "ans": 0, "exp": "(3−1)=2, 2²=4, 5×4=20, 20−4 = 16."},
        {"q": "Which value of x makes 4x − 3 = 21 true?",
         "opts": ["x = 4", "x = 5", "x = 6", "x = 7"],
         "ans": 2, "exp": "Add 3: 4x = 24. Divide by 4: x = 6. Check: 4(6)−3 = 21 ✓"},
    ],
    "Grade 6 Math — Geometry": [
        {"q": "What is the surface area of a cube with side length 4 cm?",
         "opts": ["16 cm²", "64 cm²", "96 cm²", "24 cm²"],
         "ans": 2, "exp": "6 faces. Each = 4² = 16 cm². SA = 6 × 16 = 96 cm²."},
        {"q": "A parallelogram has base 9 in and height 5 in. What is its area?",
         "opts": ["14 in²", "22.5 in²", "45 in²", "28 in²"],
         "ans": 2, "exp": "Area = base × height = 9 × 5 = 45 in²."},
        {"q": "Which point is in Quadrant II?",
         "opts": ["(3, 5)", "(−2, 4)", "(−1, −6)", "(4, −3)"],
         "ans": 1, "exp": "Q2 = (−, +). (−2, 4) is left of y-axis and above x-axis."},
        {"q": "A triangle has area 36 cm² and height 9 cm. What is the base?",
         "opts": ["4 cm", "6 cm", "8 cm", "12 cm"],
         "ans": 2, "exp": "A = ½bh → 36 = ½(b)(9) → 36 = 4.5b → b = 8 cm."},
        {"q": "A square has a side length of 9 in. What is its perimeter?",
         "opts": ["18 in", "36 in", "81 in", "27 in"],
         "ans": 1, "exp": "Perimeter = 4 × side = 4 × 9 = 36 in."},
        {"q": "Which of the following is NOT a quadrilateral?",
         "opts": ["Rectangle", "Trapezoid", "Pentagon", "Rhombus"],
         "ans": 2, "exp": "Pentagon has 5 sides. Quadrilaterals have exactly 4 sides."},
        {"q": "A rectangular prism: L=8, W=3, H=5 cm. What is its surface area?",
         "opts": ["120 cm²", "158 cm²", "190 cm²", "79 cm²"],
         "ans": 1, "exp": "SA = 2(lw+lh+wh) = 2(24+40+15) = 2(79) = 158 cm²."},
        {"q": "Plot (−2, 3) and (4, 3). What is the distance between them?",
         "opts": ["2 units", "6 units", "7 units", "1 unit"],
         "ans": 1, "exp": "Same y → horizontal: |4−(−2)| = 6 units."},
        {"q": "Trapezoid: parallel bases 10 ft and 6 ft, height 4 ft. Area?",
         "opts": ["32 ft²", "40 ft²", "24 ft²", "64 ft²"],
         "ans": 0, "exp": "A = ½(b₁+b₂)h = ½(16)(4) = 32 ft²."},
        {"q": "A prism has base area 20 cm² and height 6 cm. What is its volume?",
         "opts": ["120 cm³", "26 cm³", "240 cm³", "60 cm³"],
         "ans": 0, "exp": "V = base area × height = 20 × 6 = 120 cm³."},
        {"q": "Which point is on the y-axis?",
         "opts": ["(3, 0)", "(0, −5)", "(2, 2)", "(−4, 0)"],
         "ans": 1, "exp": "Points on the y-axis have x = 0. (0, −5) is on the y-axis."},
        {"q": "What is the distance from (1, 4) to (1, −3)?",
         "opts": ["7 units", "1 unit", "3 units", "5 units"],
         "ans": 0, "exp": "Same x → vertical: |4−(−3)| = 7 units."},
        {"q": "A triangle has vertices (0,0), (4,0), (0,3). What is its area?",
         "opts": ["12 sq units", "6 sq units", "7 sq units", "24 sq units"],
         "ans": 1, "exp": "Base = 4, height = 3. A = ½ × 4 × 3 = 6 sq units."},
        {"q": "Which describes the surface area of a 3D figure?",
         "opts": ["Total space inside", "Sum of all edges", "Sum of all face areas", "Height × Width"],
         "ans": 2, "exp": "Surface area = total area of all faces. Volume = space inside."},
        {"q": "A square has a perimeter of 28 in. What is its area?",
         "opts": ["7 in²", "14 in²", "49 in²", "196 in²"],
         "ans": 2, "exp": "Side = 28 ÷ 4 = 7 in. Area = 7² = 49 in²."},
    ],
    "Grade 6 Math — Data Analysis": [
        {"q": "Test scores: 78, 82, 91, 78, 95, 88, 82, 78. What is the mode?",
         "opts": ["82", "78", "95", "84"],
         "ans": 1, "exp": "78 appears 3 times — more than any other value."},
        {"q": "Data: 5, 8, 12, 15, 20. What is the mean?",
         "opts": ["10", "12", "13", "15"],
         "ans": 1, "exp": "Sum = 60. Count = 5. Mean = 60 ÷ 5 = 12."},
        {"q": "Why is IQR better than range when outliers are present?",
         "opts": ["IQR is always larger", "IQR uses only the middle 50% and ignores outliers",
                  "IQR includes every value", "Range can't be calculated with outliers"],
         "ans": 1, "exp": "IQR = Q3−Q1, middle 50%. Outliers pull the range but don't affect Q1 or Q3."},
        {"q": "Data: 5, 8, 8, 9, 10, 12, 15. What is the median?",
         "opts": ["8", "9", "10", "8.5"],
         "ans": 1, "exp": "7 values. Middle (4th) value = 9."},
        {"q": "What happens to the mean when a high outlier is added?",
         "opts": ["Mean always stays the same", "Mean is pulled upward", "Mean is pulled downward", "Mean becomes the outlier"],
         "ans": 1, "exp": "Outliers pull the mean toward their extreme value. A high outlier raises the mean."},
        {"q": "Ages: 10, 10, 11, 12, 12, 13, 25. Which measure best describes the center?",
         "opts": ["Mean", "Median", "Mode", "Range"],
         "ans": 1, "exp": "25 is an outlier. Median (12) is not affected by outliers and better represents the center."},
        {"q": "Stem 4 | Leaves 2, 5, 8. What is the range of these values?",
         "opts": ["3", "6", "38", "35"],
         "ans": 1, "exp": "Values are 42, 45, 48. Range = 48 − 42 = 6."},
        {"q": "In a box plot, where is the median shown?",
         "opts": ["Left edge of box", "Right edge of box", "Line inside the box", "End of right whisker"],
         "ans": 2, "exp": "The median is the vertical line INSIDE the box — it's the middle of the 5-number summary."},
        {"q": "Which type of graph best shows how scores changed over 6 months?",
         "opts": ["Bar graph", "Pie chart", "Line graph", "Box plot"],
         "ans": 2, "exp": "Line graphs show change over time — each point represents a value at a specific time."},
        {"q": "What is the MAD of: 4, 6, 8, 10?",
         "opts": ["2", "3", "4", "6"],
         "ans": 0, "exp": "Mean = 7. Deviations: |4−7|=3, |6−7|=1, |8−7|=1, |10−7|=3. MAD = (3+1+1+3)/4 = 2."},
        {"q": "Histogram: 12 in 10–19, 8 in 20–29, 15 in 30–39. Most common interval?",
         "opts": ["10–19", "20–29", "30–39", "Cannot tell"],
         "ans": 2, "exp": "30–39 has the highest frequency (15). Tallest bar = most common interval."},
        {"q": "Box plot: Min=5, Q1=10, Median=15, Q3=22, Max=30. What is the IQR?",
         "opts": ["25", "12", "15", "17"],
         "ans": 1, "exp": "IQR = Q3 − Q1 = 22 − 10 = 12."},
        {"q": "Which display shows individual values AND distribution shape?",
         "opts": ["Histogram", "Stem-and-leaf", "Box plot", "Bar graph"],
         "ans": 1, "exp": "Stem-and-leaf plots show each value while revealing the shape of the distribution."},
        {"q": "Data: 6, 6, 6, 6, 6. What is true about mean, median, and mode?",
         "opts": ["Only mode = 6", "Only median = 6", "All three equal 6", "None equal 6"],
         "ans": 2, "exp": "When all values are identical, mean = median = mode = that value. All equal 6."},
        {"q": "A data set has range = 0. What does this tell you?",
         "opts": ["The data has many outliers", "All values in the data set are the same",
                  "The mean is zero", "The data set is empty"],
         "ans": 1, "exp": "Range = Max − Min. If range = 0, then Max = Min, meaning all values are identical."},
    ],
    "Grade 6 ELA — Literary Devices": [
        {"q": "What device is used when a chapter ends with 'Little did she know, tomorrow would change everything'?",
         "opts": ["Flashback", "Foreshadowing", "Irony", "Alliteration"],
         "ans": 1, "exp": "Hinting at future events to create suspense = foreshadowing."},
        {"q": "'The classroom erupted into chaos' is an example of:",
         "opts": ["Simile", "Personification", "Metaphor", "Onomatopoeia"],
         "ans": 2, "exp": "Direct comparison (no 'like/as') of classroom to something explosive = metaphor."},
        {"q": "Which best defines verbal irony?",
         "opts": ["Saying the opposite of what you mean for effect",
                  "An event turns out opposite of what was expected",
                  "The reader knows something a character doesn't",
                  "Exaggeration for emphasis"],
         "ans": 0, "exp": "Verbal irony = saying the opposite of what you mean. 'Oh great!' when something goes wrong."},
        {"q": "What is a symbol in literature?",
         "opts": ["A figure of speech that exaggerates", "An object that represents something beyond its literal meaning",
                  "A reference to a historical event", "A comparison using 'like' or 'as'"],
         "ans": 1, "exp": "Symbol: an object/person/event that stands for something beyond itself. Dove = peace."},
        {"q": "What is an allusion?",
         "opts": ["A vision a character has", "A reference to a well-known person, place, or event",
                  "A dream sequence", "A type of rhyme scheme"],
         "ans": 1, "exp": "Allusion: indirect reference to something the reader is expected to know. 'His Achilles' heel' = weakness."},
        {"q": "What is an oxymoron?",
         "opts": ["A word that sounds like what it describes", "Two contradictory words placed together",
                  "An extreme exaggeration", "Repeating consonant sounds"],
         "ans": 1, "exp": "Oxymoron: opposite words together. 'Deafening silence,' 'bittersweet,' 'living dead.'"},
        {"q": "What is the effect of repetition in a poem?",
         "opts": ["To confuse the reader", "To emphasize ideas and create rhythm",
                  "To speed up the reading pace", "To introduce new characters"],
         "ans": 1, "exp": "Repetition emphasizes important ideas and creates musical rhythm that evokes emotion."},
        {"q": "What is a flashback?",
         "opts": ["A prediction of future events", "A hint about what will happen",
                  "A scene interrupting the present to show earlier events", "A character's dream about the future"],
         "ans": 2, "exp": "Flashback: returns the reader to an earlier time in the story to reveal backstory."},
        {"q": "Tone vs. Mood — which is correct?",
         "opts": ["They are exactly the same", "Mood = author's attitude; Tone = reader's feeling",
                  "Tone = author's attitude toward subject; Mood = feeling the text creates in the reader",
                  "Neither relates to emotion"],
         "ans": 2, "exp": "TONE = author's attitude (sarcastic, hopeful). MOOD = feeling the READER gets (eerie, joyful)."},
        {"q": "Which line uses assonance (repeated vowel sounds)?",
         "opts": ["'Sally sells seashells by the seashore'", "'The rain in Spain falls mainly on the plain'",
                  "'Pots and pans and cups and cans'", "'Dark and dreary day in December'"],
         "ans": 1, "exp": "rain/Spain/mainly/plain all share the long 'a' vowel sound — that's assonance."},
        {"q": "What is the purpose of foreshadowing?",
         "opts": ["To confuse the reader", "To create suspense and hint at future events",
                  "To explain a character's past", "To provide comic relief"],
         "ans": 1, "exp": "Foreshadowing hints at what will happen later, building suspense."},
        {"q": "What is situational irony?",
         "opts": ["Saying the opposite of what you mean", "The reader knows what a character doesn't",
                  "The opposite of what's expected actually happens", "Two characters misunderstand each other"],
         "ans": 2, "exp": "Situational irony: expected ≠ actual. A fire station burning down is situational irony."},
        {"q": "What is an extended metaphor?",
         "opts": ["A metaphor using 'like' or 'as'", "A comparison carried through an entire poem or passage",
                  "A metaphor comparing two unrelated things", "A very long simile"],
         "ans": 1, "exp": "Extended metaphor: continues for several lines or the whole text. Life described as a journey throughout a poem."},
        {"q": "'I have a ton of homework tonight!' is an example of:",
         "opts": ["Simile", "Alliteration", "Personification", "Hyperbole"],
         "ans": 3, "exp": "Extreme exaggeration for emphasis (not literally a ton) = hyperbole."},
        {"q": "What literary device gives human traits to non-human things?",
         "opts": ["Metaphor", "Simile", "Personification", "Alliteration"],
         "ans": 2, "exp": "Personification = giving human qualities to non-human objects. 'The sun smiled down on us.'"},
    ],
    "Grade 6 ELA — Reading Comprehension": [
        {"q": "What is the purpose of a topic sentence?",
         "opts": ["To conclude a paragraph", "To introduce the main idea of a paragraph",
                  "To provide evidence", "To transition between paragraphs"],
         "ans": 1, "exp": "The topic sentence introduces the main idea of the paragraph — it tells the reader what's coming."},
        {"q": "What is a primary source?",
         "opts": ["A textbook about an event", "A documentary film",
                  "A firsthand account such as a diary or letter", "An encyclopedia entry"],
         "ans": 2, "exp": "Primary sources are original firsthand materials: diaries, speeches, photographs, original documents."},
        {"q": "What does point of view affect in a story?",
         "opts": ["Only the physical setting", "What information the reader has access to",
                  "The genre of the text", "The vocabulary difficulty"],
         "ans": 1, "exp": "Point of view determines what the narrator can see and share — limiting or expanding the reader's knowledge."},
        {"q": "Which best describes the 'central idea' in an informational text?",
         "opts": ["The opening sentence", "The most important point the author develops throughout",
                  "A list of all facts", "The author's credentials"],
         "ans": 1, "exp": "The central idea = the main claim or point that the whole text supports. Not a detail — the umbrella idea."},
        {"q": "What is text evidence?",
         "opts": ["Your personal opinion", "Specific words or sentences from the text that support a claim",
                  "The author's background", "A paraphrase of the whole text"],
         "ans": 1, "exp": "Text evidence = direct quotes or specific details from the text. 'According to the text...' signals evidence."},
        {"q": "What does 'bias' mean in a text?",
         "opts": ["No opinion present", "Only facts used", "Author unfairly favors one viewpoint over others",
                  "Hard to understand"],
         "ans": 2, "exp": "Bias = one-sided presentation that favors the author's viewpoint. Readers should evaluate sources for bias."},
        {"q": "Summary vs. paraphrase — which is correct?",
         "opts": ["They are exactly the same",
                  "Summary = shorter/main ideas; Paraphrase = similar length in your own words",
                  "Paraphrase = shorter; Summary = same length", "Neither uses your own words"],
         "ans": 1, "exp": "Summary condenses to main ideas. Paraphrase restates the same info in your own words (similar length)."},
        {"q": "If a text uses 'however' between two ideas, what structure is likely?",
         "opts": ["Sequence", "Problem and solution", "Compare and contrast", "Cause and effect"],
         "ans": 2, "exp": "'However' signals a contrast — compare and contrast text structure."},
        {"q": "What is synthesis when reading multiple texts?",
         "opts": ["Reading only first and last paragraph", "Combining ideas from multiple sources into new understanding",
                  "Summarizing one text at a time", "Memorizing all facts"],
         "ans": 1, "exp": "Synthesis = combining what you've read from different sources to form a fuller, new understanding."},
        {"q": "Narrator uses he/she and knows only ONE character's thoughts. What point of view?",
         "opts": ["First person", "Third person omniscient", "Third person limited", "Second person"],
         "ans": 2, "exp": "Third person limited: he/she/they but only knows ONE character's inner life."},
        {"q": "Which requires inference rather than finding a stated fact?",
         "opts": ["What year was the Declaration signed?", "How does the character feel about moving away?",
                  "What color was the jacket?", "How many miles did they travel?"],
         "ans": 1, "exp": "Feelings are usually implied, not stated. Readers use text clues + prior knowledge to infer emotions."},
        {"q": "Which feature helps a reader find specific topics on specific pages?",
         "opts": ["Glossary", "Table of contents", "Index", "Bibliography"],
         "ans": 2, "exp": "The INDEX (alphabetical, back of book) maps topics to specific page numbers."},
        {"q": "A text describes a problem and then explains how it was solved. What structure?",
         "opts": ["Description", "Sequence", "Compare and contrast", "Problem and solution"],
         "ans": 3, "exp": "Problem and solution: the text presents an issue and then describes how it was resolved."},
        {"q": "What does 'literal vs. figurative meaning' refer to?",
         "opts": ["Hard vs. easy words", "Exact dictionary meaning vs. meaning beyond the literal",
                  "First vs. second reading", "Fiction vs. nonfiction"],
         "ans": 1, "exp": "Literal = exact/dictionary meaning. Figurative = meaning beyond literal (requires interpretation). 'It's raining cats and dogs' is figurative."},
        {"q": "Which best describes what an author does when they use 'loaded language'?",
         "opts": ["Uses very long sentences", "Chooses words with strong emotional connotations to persuade",
                  "Writes only in first person", "Avoids using any figurative language"],
         "ans": 1, "exp": "Loaded language = words chosen for strong positive or negative connotations to sway the reader's emotions."},
    ],
}


def get_question_pool(strand: str) -> list:
    """Return full deduplicated question pool for a strand (base + extra)."""
    base  = MINI_TESTS.get(strand, [])
    extra = MINI_TEST_EXTRA.get(strand, [])
    seen, pool = set(), []
    for q in base + extra:
        if q["q"] not in seen:
            seen.add(q["q"])
            pool.append(q)
    return pool


def log_staar_result(child: str, grade: int, strand: str, score: int, total: int) -> None:
    """Write a completed mini-test result to the staar_results sheet."""
    import uuid
    from datetime import date as _d
    from backend.gsheet import append_row
    append_row("staar_results", [
        str(uuid.uuid4())[:8],
        _d.today().isoformat(),
        child, grade, strand,
        score, total,
        round(score / total * 100, 1),
    ])


def get_staar_results(child: str | None = None, strand: str | None = None):
    """Return staar_results as a DataFrame, optionally filtered."""
    import pandas as pd
    from backend.gsheet import read_sheet
    df = read_sheet("staar_results")
    if df.empty:
        return df
    if child:
        df = df[df["child"].astype(str) == child]
    if strand:
        df = df[df["strand"].astype(str) == strand]
    return df

# ── Monthly study plan aligned with TEKS pacing ──────────────────────────────

STUDY_PLAN_G6 = [
    {"month": "Aug 12–Aug 31", "label": "Foundation",
     "math": ["Review integers and number classification", "Absolute value basics", "Number line activities"],
     "ela":  ["Story elements review (plot, character, theme)", "Author's purpose practice", "Reading stamina building"],
     "tip":  "Establish daily study habits early — 20 min Math + 20 min reading daily pays off by April."},
    {"month": "September", "label": "Number Operations + Narrative",
     "math": ["Integer operations (all 4)", "Fraction multiplication & division", "Decimal operations", "PEMDAS"],
     "ela":  ["Point of view identification", "Personal narrative writing", "Simile, metaphor, imagery"],
     "tip":  "Khan Academy Grade 6 Math TX — complete the Number & Operations unit this month."},
    {"month": "October", "label": "Ratios + Informational Reading",
     "math": ["Ratios and notation", "Unit rates", "Equivalent ratios and tables", "Scale drawings"],
     "ela":  ["Main idea and supporting details", "Text structures (especially cause/effect)", "Informational writing"],
     "tip":  "Fall Break Oct 12–16. Sprint before break, then light review during."},
    {"month": "November", "label": "Percent + Research Writing",
     "math": ["Converting between fractions/decimals/percents", "Tax, tip, discount", "Simple interest intro"],
     "ela":  ["Research skills: credible sources, note-taking", "MLA citations", "Informational essay draft"],
     "tip":  "Take the first Effortless Math full practice test — see where you are. Thanksgiving week: ELA reading only."},
    {"month": "December", "label": "Expressions + Argumentative",
     "math": ["Writing and evaluating expressions", "Independent vs. dependent variables", "Input/output tables"],
     "ela":  ["Claims and evidence in argument", "Counterclaims", "Argumentative essay intro"],
     "tip":  "Winter Break Dec 21: take a real break, then 30 min daily review Jan 1–3."},
    {"month": "January", "label": "Equations & Inequalities + Poetry",
     "math": ["One-step equations (all operations)", "Solving and checking equations", "Graphing inequalities"],
     "ela":  ["Figurative language deep-dive", "Poetry analysis (tone, mood, structure)", "Drama elements"],
     "tip":  "MLK Day Jan 19. Do the TEA Grade 6 interactive practice test (math) this month for the first time."},
    {"month": "February", "label": "Geometry + Comprehension Strategies",
     "math": ["Area of triangles and quadrilaterals", "Composite figures", "Surface area and nets"],
     "ela":  ["Inference from text evidence", "Context clues for vocabulary", "Cross-text comparison"],
     "tip":  "Presidents Day Feb 15. Try the TEA Grade 6 RLA interactive test. Review literary device flashcards daily."},
    {"month": "March", "label": "Volume + Argumentative Writing Polish",
     "math": ["Volume of rectangular prisms", "Coordinate plane (all 4 quadrants)", "Distance on coordinate plane"],
     "ela":  ["Full argumentative essay (draft → revise → edit)", "Peer review strategies", "Grammar: complex sentences"],
     "tip":  "Spring Break Mar 15–19. Before break: take a full timed mini-test. After break: error analysis only."},
    {"month": "April", "label": "★ STAAR Prep Sprint",
     "math": ["Data analysis: mean, median, IQR, box plots, histograms", "Personal financial literacy", "FULL released tests daily"],
     "ela":  ["STAAR format practice: literary + informational paired passages", "Extended response practice", "Grammar speed review"],
     "tip":  "★ STAAR Reading ~Apr 6  |  ★ STAAR Math ~Apr 8\nFinal week: sleep 9 hrs, eat breakfast, review formulas only."},
    {"month": "May", "label": "Post-STAAR + Grade 7 Preview",
     "math": ["Financial literacy projects", "Spiral review of weakest strands", "Grade 7 preview: proportional relationships"],
     "ela":  ["Independent reading choice book", "Oral presentation skills", "Portfolio reflection"],
     "tip":  "Last Day May 28. Celebrate STAAR completion! Keep reading over summer."},
]

# ── STAAR exam dates (Spring 2026 approximate) ────────────────────────────────
# Dates follow TEA's typical April testing window.
# Verify exact dates at fisd.net or tea.texas.gov each year.
from datetime import date as _date

STAAR_DATES_2026 = [
    {"date": _date(2026, 4, 6),  "label": "STAAR RLA",
     "grades": "6 & 7", "subject": "Reading & Language Arts",
     "full": "STAAR RLA — Grades 6 & 7 (approx. · verify at fisd.net)"},
    {"date": _date(2026, 4, 8),  "label": "STAAR Math",
     "grades": "6 & 7", "subject": "Mathematics",
     "full": "STAAR Math — Grades 6 & 7 (approx. · verify at fisd.net)"},
    {"date": _date(2026, 4, 22), "label": "STAAR RLA",
     "grades": "8", "subject": "Reading & Language Arts",
     "full": "STAAR RLA — Grade 8 (approx. · verify at fisd.net)"},
    {"date": _date(2026, 4, 23), "label": "STAAR Math",
     "grades": "8", "subject": "Mathematics",
     "full": "STAAR Math — Grade 8 (approx. · verify at fisd.net)"},
    {"date": _date(2026, 4, 24), "label": "STAAR Science",
     "grades": "8", "subject": "Science",
     "full": "STAAR Science — Grade 8 (approx. · verify at fisd.net)"},
]
