"""STAAR Prep data — resources, flashcards, mini-test questions for Grades 6-8.

Sources:
  Official tests  : tea.texas.gov / txpt.cambiumtds.com
  Khan Academy    : khanacademy.org (TX TEKS-aligned)
  Texas Gateway   : texasgateway.org
  Effortless Math : effortlessmath.com
  Quizlet / TXST  : flashcard sets
  Albert.io       : STAAR practice
"""

# ── Curated resource links by grade ──────────────────────────────────────────

RESOURCES = {
    6: {
        "Math": {
            "Official Practice Tests": [
                {"name": "Grade 6 Math — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-MA-2024-6&skipIntoTest=true&grade=6",
                 "note": "Official TEA online test · mirrors real STAAR format", "free": True},
                {"name": "2023 Grade 6 Math Practice Test PDF (TEA)",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2023-staar-redesign-6-math-practice-test.pdf",
                 "note": "Printable released practice test", "free": True},
                {"name": "TEA STAAR Released Test Questions Hub",
                 "url":  "https://tea.texas.gov/student-assessment/staar/staar-released-test-questions",
                 "note": "All released tests by grade and year", "free": True},
            ],
            "Khan Academy": [
                {"name": "Grade 6 Math — TX TEKS Aligned (Khan Academy)",
                 "url":  "https://www.khanacademy.org/math/grade-6-math-tx",
                 "note": "Video lessons + practice problems mapped to TEKS §111.26", "free": True},
            ],
            "Free Worksheets": [
                {"name": "Grade 6 STAAR Math Worksheets (Effortless Math)",
                 "url":  "https://www.effortlessmath.com/blog/grade-6-staar-math-worksheets/",
                 "note": "Strand-by-strand free worksheets", "free": True},
                {"name": "Free Grade 6 STAAR Math Practice Test (Effortless Math)",
                 "url":  "https://www.effortlessmath.com/math-topics/free-grade-6-staar-math-practice-test/",
                 "note": "Full practice test, no account needed", "free": True},
                {"name": "Grade 6 Math STAAR Worksheets (New Path Worksheets)",
                 "url":  "https://newpathworksheets.com/math/grade-6/texas-assessments-standards-staar",
                 "note": "Printable by TEKS standard", "free": True},
                {"name": "Texas Gateway — Grade 6 OER Math",
                 "url":  "https://texasgateway.org/book/grade-6-oer-math-edition-1",
                 "note": "Official OER textbook, free", "free": True},
            ],
            "Flashcards": [
                {"name": "Grade 6 Math STAAR Flashcards (Quizlet)",
                 "url":  "https://quizlet.com/206513731/6th-grade-math-staar-practice-flash-cards/",
                 "note": "Digital flashcards for key terms and concepts", "free": True},
                {"name": "Grade 6 Math TEKS Flashcards (TXST Mathworks)",
                 "url":  "https://www.txst.edu/mathworks/mathworks-curriculum/math-explorations-curriculum/online-learning-tools/staar-math-practice-questions/6th-grade-math-teks-online-flashcards.html",
                 "note": "Texas State University interactive flashcards", "free": True},
            ],
            "Practice Platforms": [
                {"name": "Albert.io — Grade 6 STAAR Math",
                 "url":  "https://www.albert.io/staar-grade-6-math",
                 "note": "Adaptive practice with explanations (free + paid tiers)", "free": False},
                {"name": "Union Test Prep — STAAR",
                 "url":  "https://uniontestprep.com/staar-test",
                 "note": "Free practice questions with explanations", "free": True},
                {"name": "MathHelp — Grade 6 STAAR Math",
                 "url":  "https://www.mathhelp.com/staar-math-test-prep/",
                 "note": "Video lessons + practice, free trial", "free": False},
            ],
        },
        "ELA / RLA": {
            "Official Practice Tests": [
                {"name": "Grade 6 RLA — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-ELA-Reading_2024-6&skipIntoTest=true&grade=6",
                 "note": "Official TEA online RLA test · real format", "free": True},
                {"name": "TEA STAAR Released Test Questions Hub",
                 "url":  "https://tea.texas.gov/student-assessment/staar/staar-released-test-questions",
                 "note": "All released RLA tests by grade and year", "free": True},
            ],
            "Khan Academy": [
                {"name": "Reading & Language Arts (Khan Academy)",
                 "url":  "https://www.khanacademy.org/ela/cc-6th-reading-vocab",
                 "note": "Grammar, vocabulary, reading comprehension practice", "free": True},
            ],
            "Free Worksheets": [
                {"name": "Texas Gateway — ELA Resources",
                 "url":  "https://texasgateway.org/",
                 "note": "Search 'Grade 6 ELA' for TEKS-aligned lessons", "free": True},
                {"name": "Albert.io — Grade 6 STAAR RLA",
                 "url":  "https://www.albert.io/staar-grade-6-rla",
                 "note": "Reading comprehension + grammar practice", "free": False},
            ],
            "Flashcards": [
                {"name": "Grade 6 ELA Literary Terms (Quizlet)",
                 "url":  "https://quizlet.com/subject/6th-grade-ela/",
                 "note": "Multiple sets for literary devices, grammar, vocabulary", "free": True},
            ],
        },
    },
    7: {
        "Math": {
            "Official Practice Tests": [
                {"name": "Grade 7 Math — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-MA-2024-7&skipIntoTest=true&grade=7",
                 "note": "Official TEA online test", "free": True},
                {"name": "2024 Grade 7 Math Answer Key (TEA)",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2024-staar-7-math-key.pdf",
                 "note": "Answer key for released test", "free": True},
                {"name": "TEA STAAR Released Test Questions Hub",
                 "url":  "https://tea.texas.gov/student-assessment/staar/staar-released-test-questions",
                 "note": "All released tests", "free": True},
            ],
            "Khan Academy": [
                {"name": "Grade 7 Math — TX TEKS Aligned (Khan Academy)",
                 "url":  "https://www.khanacademy.org/math/grade-7-math-tx",
                 "note": "Proportional relationships, expressions, geometry", "free": True},
            ],
            "Free Worksheets": [
                {"name": "Grade 7 STAAR Math Worksheets (Effortless Math)",
                 "url":  "https://www.effortlessmath.com/blog/staar-7-math-worksheets/",
                 "note": "Free strand-aligned worksheets", "free": True},
                {"name": "Free Grade 7 STAAR Math Practice Test",
                 "url":  "https://www.effortlessmath.com/math-topics/free-grade-7-staar-math-practice-test/",
                 "note": "Full free practice test", "free": True},
            ],
            "Practice Platforms": [
                {"name": "Albert.io — Grade 7 STAAR Math",
                 "url":  "https://www.albert.io/staar-grade-7-math",
                 "note": "Adaptive practice with rationale", "free": False},
                {"name": "MathHelp — Grade 7 STAAR Math",
                 "url":  "https://www.mathhelp.com/staar-grade-7-math-test-prep/",
                 "note": "Video lessons + practice", "free": False},
            ],
        },
        "ELA / RLA": {
            "Official Practice Tests": [
                {"name": "Grade 7 RLA — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-ELA-Reading_2024-7&skipIntoTest=true&grade=7",
                 "note": "Official TEA online RLA test", "free": True},
                {"name": "2024 Grade 7 RLA Answer Key (TEA)",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2024-staar-7-rla-key.pdf",
                 "note": "Answer key PDF", "free": True},
            ],
        },
    },
    8: {
        "Math": {
            "Official Practice Tests": [
                {"name": "Grade 8 Math — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-MA-2024-8&skipIntoTest=true&grade=8",
                 "note": "Official TEA online test", "free": True},
                {"name": "2023 Grade 8 Math Practice Test PDF",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2023-staar-redesign-8-math-practice-test.pdf",
                 "note": "Printable released test", "free": True},
                {"name": "2024 Grade 8 Math Answer Key",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2024-staar-8-math-key.pdf",
                 "note": "Answer key PDF", "free": True},
            ],
            "Khan Academy": [
                {"name": "Grade 8 Math — TX TEKS Aligned (Khan Academy)",
                 "url":  "https://www.khanacademy.org/math/grade-8-math-tx",
                 "note": "Linear equations, functions, geometry, statistics", "free": True},
            ],
            "Free Worksheets": [
                {"name": "Grade 8 STAAR Math Worksheets (Effortless Math)",
                 "url":  "https://www.effortlessmath.com/blog/staar-8-math-worksheets/",
                 "note": "Free strand-aligned worksheets", "free": True},
                {"name": "Free Grade 8 STAAR Math Practice Test",
                 "url":  "https://www.effortlessmath.com/math-topics/free-grade-8-staar-math-practice-test/",
                 "note": "Full free practice test", "free": True},
                {"name": "Grade 8 Math STAAR (New Path Worksheets)",
                 "url":  "https://newpathworksheets.com/math/grade-8/texas-assessments-standards-staar",
                 "note": "Printable by TEKS standard", "free": True},
            ],
            "Practice Platforms": [
                {"name": "Albert.io — Grade 8 STAAR Math",
                 "url":  "https://www.albert.io/staar-grade-8-math",
                 "note": "Adaptive practice with rationale", "free": False},
                {"name": "MathHelp — Grade 8 STAAR Math",
                 "url":  "https://www.mathhelp.com/staar-grade-8-math-test-prep/",
                 "note": "Video lessons + practice", "free": False},
            ],
        },
        "ELA / RLA": {
            "Official Practice Tests": [
                {"name": "Grade 8 RLA — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-ELA-Reading_2024-8&skipIntoTest=true&grade=8",
                 "note": "Official TEA online RLA test", "free": True},
                {"name": "2024 Grade 8 RLA Answer Key",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2024-staar-8-rla-key.pdf",
                 "note": "Answer key PDF", "free": True},
            ],
            "Practice Platforms": [
                {"name": "Albert.io — Grade 8 STAAR RLA",
                 "url":  "https://www.albert.io/staar-grade-8-rla",
                 "note": "Adaptive reading practice", "free": False},
            ],
        },
        "Science": {
            "Official Practice Tests": [
                {"name": "Grade 8 Science — Interactive Practice Test (TEA)",
                 "url":  "https://txpt.cambiumtds.com/student/?testId=TXPT-GEN-PRAC-UD-SC-2024-8&skipIntoTest=true&grade=8",
                 "note": "Official TEA online science test", "free": True},
                {"name": "2023 Grade 8 Science Practice Test PDF",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2023-staar-redesign-8-science-practice-test.pdf",
                 "note": "Printable released test", "free": True},
                {"name": "2024 Grade 8 Science Practice Test Key",
                 "url":  "https://tea.texas.gov/student-assessment/staar/released-test-questions/2024-staar-8-science-practice-test-key.pdf",
                 "note": "Answer key PDF", "free": True},
            ],
            "Free Worksheets": [
                {"name": "Grade 8 Science STAAR (New Path Worksheets)",
                 "url":  "https://newpathworksheets.com/science/grade-8/texas-assessments-standards-staar",
                 "note": "Printable by TEKS standard", "free": True},
                {"name": "Albert.io — Grade 8 STAAR Science",
                 "url":  "https://www.albert.io/staar-grade-8-science",
                 "note": "Practice questions with explanations", "free": False},
            ],
        },
    },
}

# ── Flashcards — Grade 6 Math (aligned to TEKS §111.26) ─────────────────────

FLASHCARDS = {
    "Grade 6 Math": [
        # ── Number & Operations ───────────────────────────────────────────────
        {"q": "What is a rational number?",
         "a": "Any number that can be written as a fraction p/q where p and q are integers and q ≠ 0.\nIncludes: integers, fractions, terminating and repeating decimals.\nExamples: −3, ½, 0.75, −2.6̄",
         "strand": "Number & Operations"},
        {"q": "What is absolute value?",
         "a": "The distance of a number from 0 on a number line. Always ≥ 0.\n|−8| = 8   |5| = 5   |0| = 0",
         "strand": "Number & Operations"},
        {"q": "Rules for multiplying/dividing integers?",
         "a": "Same signs → Positive result\nDifferent signs → Negative result\n(−3) × (−4) = +12  |  (−3) × 4 = −12\n12 ÷ (−3) = −4  |  (−12) ÷ (−3) = +4",
         "strand": "Number & Operations"},
        {"q": "How do you add/subtract fractions with unlike denominators?",
         "a": "1. Find the Least Common Denominator (LCD)\n2. Rewrite each fraction with LCD\n3. Add/subtract numerators, keep denominator\n½ + ⅓ → LCD=6 → 3/6 + 2/6 = 5/6",
         "strand": "Number & Operations"},
        {"q": "How do you multiply fractions?",
         "a": "Multiply numerators × numerators, denominators × denominators. Simplify.\n¾ × ⅔ = (3×2)/(4×3) = 6/12 = ½",
         "strand": "Number & Operations"},
        {"q": "How do you divide fractions?",
         "a": "Keep the first fraction, Change ÷ to ×, Flip (reciprocal) the second fraction.\nKCF: ¾ ÷ ⅔ = ¾ × 3/2 = 9/8 = 1⅛",
         "strand": "Number & Operations"},
        {"q": "What is the Order of Operations (PEMDAS)?",
         "a": "Parentheses → Exponents → Multiply/Divide (left to right) → Add/Subtract (left to right)\n2 + 3 × 4 = 2 + 12 = 14  (NOT 20)",
         "strand": "Number & Operations"},
        # ── Proportionality ───────────────────────────────────────────────────
        {"q": "What is a ratio, and what are the 3 ways to write it?",
         "a": "A comparison of two quantities.\n3 ways: 3 to 4  |  3:4  |  3/4",
         "strand": "Proportionality"},
        {"q": "What is a unit rate?",
         "a": "A ratio with a denominator of 1, showing the rate per ONE unit.\n$2.50 per gallon  |  60 miles per hour\nDivide both parts by the denominator value.",
         "strand": "Proportionality"},
        {"q": "How do you find percent of a number?",
         "a": "Multiply the number by the percent written as a decimal.\n25% of 80 = 0.25 × 80 = 20\nOr: (percent/100) × whole = part",
         "strand": "Proportionality"},
        {"q": "How do you convert between fractions, decimals, and percents?",
         "a": "Fraction → Decimal: divide numerator by denominator (¾ = 0.75)\nDecimal → Percent: multiply by 100 (0.75 = 75%)\nPercent → Decimal: divide by 100 (35% = 0.35)\nPercent → Fraction: write over 100 and simplify (35% = 35/100 = 7/20)",
         "strand": "Proportionality"},
        {"q": "How do you calculate a discount/sale price?",
         "a": "Discount Amount = Original Price × Discount %\nSale Price = Original Price − Discount Amount\nExample: $60 shirt, 20% off → Discount = $12 → Sale Price = $48",
         "strand": "Proportionality"},
        {"q": "How do you calculate tax and tip?",
         "a": "Tax/Tip Amount = Original × Rate\nTotal = Original + Tax/Tip\nExample: $40 bill, 8% tax → Tax = $3.20 → Total = $43.20",
         "strand": "Proportionality"},
        # ── Expressions, Equations & Relationships ───────────────────────────
        {"q": "What is the difference between an expression and an equation?",
         "a": "Expression: no equal sign — just variables, numbers, operations (3x + 5)\nEquation: has an equal sign — states two things are equal (3x + 5 = 20)",
         "strand": "Expressions & Equations"},
        {"q": "What is the Distributive Property?",
         "a": "a(b + c) = ab + ac\nExamples:\n3(x + 4) = 3x + 12\n−2(5 − y) = −10 + 2y\nUse to expand or factor expressions.",
         "strand": "Expressions & Equations"},
        {"q": "How do you solve a one-step equation?",
         "a": "Use inverse operations to isolate the variable. Do the same to BOTH sides.\nx + 7 = 15 → subtract 7 → x = 8\nx − 4 = 9  → add 4 → x = 13\n3x = 21    → divide by 3 → x = 7\nx/5 = 4   → multiply by 5 → x = 20",
         "strand": "Expressions & Equations"},
        {"q": "What are independent and dependent variables?",
         "a": "Independent variable (x): the INPUT — you choose its value\nDependent variable (y): the OUTPUT — its value DEPENDS on x\nExample: hours worked (x) → money earned (y)",
         "strand": "Expressions & Equations"},
        {"q": "How do you write an inequality and graph it on a number line?",
         "a": "< less than (open circle, arrow left)\n> greater than (open circle, arrow right)\n≤ less than or equal (closed circle, arrow left)\n≥ greater than or equal (closed circle, arrow right)\nExample: x > 3 → open circle at 3, arrow pointing right",
         "strand": "Expressions & Equations"},
        # ── Geometry ─────────────────────────────────────────────────────────
        {"q": "Area formulas — triangle, parallelogram, trapezoid?",
         "a": "Triangle: A = ½ × base × height\nParallelogram: A = base × height\nTrapezoid: A = ½ × (b₁ + b₂) × height\nRemember: height must be PERPENDICULAR to the base",
         "strand": "Geometry"},
        {"q": "How do you find area of a composite figure?",
         "a": "Break it into familiar shapes (rectangles, triangles, etc.).\nAdd or subtract the areas of each piece.\nLabel each part carefully before calculating.",
         "strand": "Geometry"},
        {"q": "Volume of a rectangular prism?",
         "a": "V = length × width × height\nV = l × w × h\nUnits are CUBIC (cm³, in³, ft³)\nExample: 5 × 4 × 3 = 60 in³",
         "strand": "Geometry"},
        {"q": "How do you find surface area of a rectangular prism?",
         "a": "SA = 2(lw + lh + wh)\nOr draw the net: 6 rectangles, add up all 6 areas.\nUnits are SQUARE (cm², in²)",
         "strand": "Geometry"},
        {"q": "Coordinate plane: quadrants and plotting points?",
         "a": "Q1: (+, +) — right of y, above x\nQ2: (−, +) — left of y, above x\nQ3: (−, −) — left of y, below x\nQ4: (+, −) — right of y, below x\nPlot (x, y): move x units horizontally, then y units vertically",
         "strand": "Geometry"},
        # ── Data Analysis ─────────────────────────────────────────────────────
        {"q": "What are mean, median, mode, and range?",
         "a": "Mean: sum ÷ count (average)\nMedian: middle value when sorted (if even count, average the 2 middles)\nMode: most frequent value(s)\nRange: max − min\nData: 3, 7, 7, 9, 14 → Mean=8, Median=7, Mode=7, Range=11",
         "strand": "Data Analysis"},
        {"q": "What is the IQR and why does it matter?",
         "a": "IQR = Q3 − Q1 (Interquartile Range)\nMeasures the spread of the MIDDLE 50% of data.\nResistant to outliers (unlike range).\nQ1 = median of lower half | Q3 = median of upper half",
         "strand": "Data Analysis"},
        {"q": "What does a box plot show?",
         "a": "5-number summary:\n• Minimum (left whisker end)\n• Q1 (left edge of box)\n• Median (line inside box)\n• Q3 (right edge of box)\n• Maximum (right whisker end)\nBox width = IQR",
         "strand": "Data Analysis"},
        {"q": "Dot plot vs. histogram vs. stem-and-leaf — when to use each?",
         "a": "Dot plot: small data sets, see individual values, find clusters\nHistogram: large data sets grouped into intervals, see distribution shape\nStem-and-leaf: shows individual values AND distribution; good for comparing two data sets (back-to-back)",
         "strand": "Data Analysis"},
        {"q": "What is a statistical question?",
         "a": "A question that EXPECTS variability in the answers — different people would give different responses.\nStatistical: 'How many hours do 6th graders sleep per night?'\nNot statistical: 'How many hours did I sleep last night?'",
         "strand": "Data Analysis"},
        # ── Financial Literacy ────────────────────────────────────────────────
        {"q": "What is simple interest? Formula?",
         "a": "I = P × R × T\nI = Interest earned/paid\nP = Principal (starting amount)\nR = Annual interest Rate (as decimal)\nT = Time in years\nExample: $1,000 at 5% for 3 years → I = 1000 × 0.05 × 3 = $150",
         "strand": "Financial Literacy"},
        {"q": "Gross income vs. Net income?",
         "a": "Gross Income: total earnings BEFORE any deductions\nNet Income (Take-Home Pay): earnings AFTER taxes and deductions\nDeductions include: federal/state income tax, Social Security, Medicare, health insurance",
         "strand": "Financial Literacy"},
        {"q": "What is a credit score and why does it matter?",
         "a": "A number (300–850) measuring how reliably you repay borrowed money.\nHigher score → better loan rates, easier to rent/borrow\nAffected by: payment history, credit utilization, length of credit history, new accounts\n720+ = Good | 800+ = Excellent",
         "strand": "Financial Literacy"},
    ],
    "Grade 6 ELA": [
        # ── Literary Devices ──────────────────────────────────────────────────
        {"q": "Simile vs. Metaphor — what's the difference?",
         "a": "Simile: comparison using 'like' or 'as'\n  → 'She runs like the wind.'\nMetaphor: direct comparison WITHOUT 'like/as'\n  → 'He is a lion in battle.'",
         "strand": "Literary Devices"},
        {"q": "What is personification?",
         "a": "Giving human qualities, feelings, or actions to non-human things.\n→ 'The stars winked at us.'\n→ 'The storm roared and screamed all night.'",
         "strand": "Literary Devices"},
        {"q": "What is alliteration?",
         "a": "Repetition of the same consonant SOUND at the beginning of nearby words.\n→ 'Peter Piper picked a peck of pickled peppers.'\n→ 'Silly Sally swiftly shooed sheep.'",
         "strand": "Literary Devices"},
        {"q": "What is onomatopoeia?",
         "a": "Words that SOUND like what they describe.\n→ buzz, crash, sizzle, hiss, whoosh, bang\nUsed to make writing more vivid and sensory.",
         "strand": "Literary Devices"},
        {"q": "What is hyperbole?",
         "a": "An extreme exaggeration used for emphasis or humor (not meant literally).\n→ 'I've told you a million times!'\n→ 'I'm so hungry I could eat a horse.'",
         "strand": "Literary Devices"},
        {"q": "What is imagery?",
         "a": "Descriptive language that appeals to the 5 senses to create a mental picture.\nSight, Sound, Touch, Taste, Smell\n→ 'The warm, golden light filtered through the dusty curtains.'",
         "strand": "Literary Devices"},
        {"q": "What is foreshadowing?",
         "a": "Hints or clues in the text that suggest what will happen later in the story.\n→ Dark clouds gathering before a storm in the plot\n→ A character saying 'I have a bad feeling about this'\nCreates suspense and tension.",
         "strand": "Literary Devices"},
        {"q": "What is irony? Name the 3 types.",
         "a": "Verbal irony: saying the opposite of what you mean (sarcasm)\nSituational irony: the opposite of what's expected happens\nDramatic irony: the audience knows something the character doesn't",
         "strand": "Literary Devices"},
        # ── Reading / Comprehension ───────────────────────────────────────────
        {"q": "What are the 5 text structures? Give signal words for each.",
         "a": "1. Description: for example, specifically, such as\n2. Sequence/Chronological: first, next, then, finally\n3. Compare & Contrast: similarly, however, on the other hand, both\n4. Cause & Effect: because, therefore, as a result, so, since\n5. Problem & Solution: the problem is, one solution, as a result",
         "strand": "Comprehension"},
        {"q": "What is the author's purpose (PIE)?",
         "a": "P — Persuade: convince the reader of an opinion\nI — Inform: teach or explain facts/information\nE — Entertain: engage or amuse the reader\nMany texts have more than one purpose!",
         "strand": "Comprehension"},
        {"q": "What is a main idea vs. a supporting detail?",
         "a": "Main Idea: the most important point the author makes about the topic — the 'umbrella idea'\nSupporting Details: facts, examples, and explanations that back up the main idea\nTip: Ask 'What is this MOSTLY about?' → main idea",
         "strand": "Comprehension"},
        {"q": "How do you make an inference?",
         "a": "Inference = Text Evidence + Your Prior Knowledge\nYou read BETWEEN the lines — the author implies it but doesn't state it directly.\nAsk: What do I notice in the text? What do I already know? What can I conclude?",
         "strand": "Comprehension"},
        {"q": "What is point of view? Types?",
         "a": "1st Person: narrator IS a character — uses I, me, my, we\n3rd Person Limited: narrator tells one character's thoughts\n3rd Person Omniscient: narrator knows ALL characters' thoughts\n2nd Person: uses 'you' (rare in literature)",
         "strand": "Comprehension"},
        {"q": "What is theme vs. topic?",
         "a": "Topic: what the story is ABOUT (friendship, loyalty, courage)\nTheme: the MESSAGE or life lesson the author conveys about the topic\nTopic = 'courage' | Theme = 'True courage means acting even when you're afraid.'\nTheme is a COMPLETE SENTENCE with a lesson.",
         "strand": "Comprehension"},
        # ── Writing ───────────────────────────────────────────────────────────
        {"q": "What are the 3 types of writing tested on STAAR?",
         "a": "1. Narrative: tells a story (real or imagined), engages reader with plot/characters\n2. Informational/Explanatory: explains or teaches using facts\n3. Argumentative: makes a claim and supports it with evidence to persuade",
         "strand": "Writing"},
        {"q": "What is a thesis statement?",
         "a": "A sentence (usually at the end of the introduction) that states the main argument or central idea of an essay.\nStrong thesis: specific, debatable, answers 'so what?'\nWeak: 'I will discuss climate change.'\nStrong: 'Stricter recycling laws are essential to reducing plastic pollution in our oceans.'",
         "strand": "Writing"},
        {"q": "What is a counterclaim and why include it?",
         "a": "A counterclaim is the OPPOSING view to your argument.\nInclude it to show you understand multiple perspectives — then REFUTE it.\nStructure: 'Some may argue that ___. However, ___'\nShows sophisticated thinking and strengthens your argument.",
         "strand": "Writing"},
        {"q": "How do you integrate a quote into your writing?",
         "a": "Quote Sandwich:\n1. Introduce: Name the source or context\n2. Insert: Include the quote in quotation marks\n3. Explain: Tell the reader WHY this quote supports your point\n→ 'According to the article, \"...\" This shows that...'",
         "strand": "Writing"},
        # ── Grammar / Language ────────────────────────────────────────────────
        {"q": "What are the 8 parts of speech?",
         "a": "Noun (person, place, thing, idea)\nPronoun (replaces noun: he, she, they)\nVerb (action or state of being)\nAdjective (modifies noun)\nAdverb (modifies verb/adjective/adverb)\nPreposition (shows relationship: in, on, under)\nConjunction (connects: FANBOYS + AAAWWUBBIS)\nInterjection (expresses emotion: Wow! Oh!)",
         "strand": "Grammar"},
        {"q": "What is a complex sentence? How do you punctuate it?",
         "a": "Has one independent clause + one or more dependent clauses.\nDependent clause starts with subordinating conjunction (because, although, when, if, since...)\nIF dependent clause comes FIRST → use a comma after it\n→ 'Although it rained, we played outside.'\nIF independent clause comes first → NO comma\n→ 'We played outside although it rained.'",
         "strand": "Grammar"},
        {"q": "Connotation vs. Denotation?",
         "a": "Denotation: the literal, dictionary definition of a word\nConnotation: the emotional feeling or association a word carries\nExample: 'thin' vs. 'skinny' vs. 'slender'\n→ All mean the same thing (denotation), but have different feelings (connotation)",
         "strand": "Grammar"},
    ],
    "Grade 7 Math": [
        {"q": "What is a proportional relationship?",
         "a": "A relationship where two quantities increase/decrease at a constant rate (constant of proportionality k).\ny = kx — graph is a straight line through the ORIGIN\nk = y/x (unit rate)\nExample: $5.50 per pound → y = 5.5x",
         "strand": "Proportionality"},
        {"q": "How do you find percent increase or decrease?",
         "a": "% Change = (New − Old) / Old × 100\nIncrease: (New > Old) → positive %\nDecrease: (New < Old) → negative %\nExample: price goes from $80 to $100 → (100−80)/80 × 100 = 25% increase",
         "strand": "Proportionality"},
        {"q": "What is simple interest?",
         "a": "I = PRT\nP = Principal, R = Rate (decimal), T = Time (years)\nTotal Amount = P + I\nExample: $500 at 4% for 2 years → I = 500 × 0.04 × 2 = $40",
         "strand": "Financial Literacy"},
        {"q": "How do you solve two-step equations?",
         "a": "Work BACKWARDS using inverse operations — undo addition/subtraction first, then multiplication/division.\n2x + 5 = 17 → subtract 5 → 2x = 12 → divide by 2 → x = 6\nAlways check: 2(6) + 5 = 17 ✓",
         "strand": "Expressions & Equations"},
        {"q": "What is the circumference of a circle?",
         "a": "C = 2πr  or  C = πd\nr = radius, d = diameter, π ≈ 3.14159\nExample: circle with radius 5 → C = 2 × π × 5 ≈ 31.4 units",
         "strand": "Geometry"},
        {"q": "What is the area of a circle?",
         "a": "A = πr²\nr = radius (half the diameter)\nExample: circle with radius 4 → A = π × 4² = 16π ≈ 50.3 sq units",
         "strand": "Geometry"},
        {"q": "Supplementary vs. Complementary angles?",
         "a": "Complementary: two angles that add to 90°\nSupplementary: two angles that add to 180°\nMemory trick: C comes before S alphabetically, 90° comes before 180°",
         "strand": "Geometry"},
        {"q": "What are the measures of central tendency vs. variability?",
         "a": "Central tendency: Mean, Median, Mode (where is the CENTER?)\nVariability: Range, IQR, MAD (how SPREAD OUT is the data?)\nMAD (Mean Absolute Deviation) = average distance of each value from the mean",
         "strand": "Data Analysis"},
    ],
    "Grade 8 Math": [
        {"q": "What is slope and how do you calculate it?",
         "a": "Slope (m) = rise/run = (y₂ − y₁)/(x₂ − x₁)\nSlope tells how steep a line is and its direction.\nPositive slope: line goes up left to right\nNegative slope: line goes down left to right\nZero slope: horizontal line | Undefined: vertical line",
         "strand": "Proportionality"},
        {"q": "What is slope-intercept form?",
         "a": "y = mx + b\nm = slope (rate of change)\nb = y-intercept (where line crosses y-axis)\nExample: y = 2x + 3 → slope is 2, y-intercept is (0, 3)",
         "strand": "Proportionality"},
        {"q": "What is the Pythagorean Theorem?",
         "a": "a² + b² = c²\nFor right triangles: a and b are the LEGS, c is the HYPOTENUSE (longest side, opposite right angle)\nFind missing side: c = √(a² + b²)\nExample: legs 3 and 4 → c = √(9+16) = √25 = 5",
         "strand": "Geometry"},
        {"q": "What is scientific notation?",
         "a": "A way to write very large or small numbers.\nForm: a × 10ⁿ where 1 ≤ a < 10\n45,000 = 4.5 × 10⁴\n0.0032 = 3.2 × 10⁻³\nPositive exponent → large number\nNegative exponent → small number",
         "strand": "Number & Operations"},
        {"q": "What is a linear vs. non-linear function?",
         "a": "Linear: rate of change is CONSTANT → graph is a straight line → y = mx + b\nNon-linear: rate of change varies → graph is curved\nCheck: if the table shows equal changes in x but NOT equal changes in y → non-linear",
         "strand": "Expressions & Equations"},
        {"q": "How do you solve equations with variables on both sides?",
         "a": "1. Distribute if needed\n2. Combine like terms on each side\n3. Move all variables to one side (add/subtract)\n4. Solve for the variable\n5x + 3 = 2x + 12 → 3x = 9 → x = 3",
         "strand": "Expressions & Equations"},
        {"q": "Volume formulas: cylinder, cone, sphere?",
         "a": "Cylinder: V = πr²h\nCone: V = ⅓πr²h  (1/3 of cylinder)\nSphere: V = 4/3 πr³\nRemember: Cone = 1/3 Cylinder with same r and h",
         "strand": "Geometry"},
        {"q": "What is a transformation? Name the 4 types.",
         "a": "A change in position or size of a figure.\n1. Translation: slide (shift)\n2. Reflection: flip (mirror image)\n3. Rotation: turn around a point\n4. Dilation: resize (scale up or down)\nFirst 3 are rigid motions (preserve size/shape).",
         "strand": "Geometry"},
    ],
}

# ── Mini-test questions (STAAR-style MCQ) ────────────────────────────────────

MINI_TESTS = {
    "Grade 6 Math — Number & Operations": [
        {"q": "Which list shows the numbers in order from LEAST to GREATEST?",
         "opts": ["−3, 0, −½, ¼, 2", "−3, −½, 0, ¼, 2", "2, ¼, 0, −½, −3", "0, −½, −3, ¼, 2"],
         "ans": 1, "exp": "On a number line: −3 is furthest left, then −½, then 0, then ¼, then 2."},
        {"q": "What is the value of −24 ÷ (−6)?",
         "opts": ["−4", "−18", "4", "18"],
         "ans": 2, "exp": "Negative ÷ Negative = Positive. 24 ÷ 6 = 4."},
        {"q": "Which of the following is a rational number but NOT an integer?",
         "opts": ["−5", "0", "¾", "12"],
         "ans": 2, "exp": "Integers are whole numbers and their negatives. ¾ is a fraction — rational but not an integer."},
        {"q": "What is |−17| + |−8|?",
         "opts": ["−25", "−9", "9", "25"],
         "ans": 3, "exp": "|−17| = 17 and |−8| = 8. Their sum = 25."},
        {"q": "Evaluate: 3 + 4 × 2² − 6 ÷ 3",
         "opts": ["12", "17", "15", "11"],
         "ans": 2, "exp": "PEMDAS: 2²=4, then 4×4=16, then 6÷3=2, then 3+16−2 = 17."},
    ],
    "Grade 6 Math — Proportionality": [
        {"q": "A car travels 156 miles in 3 hours. What is the unit rate in miles per hour?",
         "opts": ["48 mph", "52 mph", "46.8 mph", "468 mph"],
         "ans": 1, "exp": "156 ÷ 3 = 52 miles per hour."},
        {"q": "A shirt originally costs $40. It is on sale for 25% off. What is the sale price?",
         "opts": ["$10", "$25", "$30", "$35"],
         "ans": 2, "exp": "Discount = 25% × $40 = $10. Sale price = $40 − $10 = $30."},
        {"q": "Which represents 35% written as a fraction in simplest form?",
         "opts": ["35/10", "7/20", "3/5", "7/2"],
         "ans": 1, "exp": "35% = 35/100. GCF of 35 and 100 is 5. 35/100 = 7/20."},
        {"q": "Juice boxes cost $6 for a pack of 8. What is the unit cost per juice box?",
         "opts": ["$0.65", "$0.75", "$0.80", "$1.33"],
         "ans": 1, "exp": "$6 ÷ 8 = $0.75 per juice box."},
        {"q": "A recipe uses 2½ cups of flour for every 36 cookies. How many cups are needed for 108 cookies?",
         "opts": ["5", "6½", "7½", "9"],
         "ans": 2, "exp": "108 ÷ 36 = 3. So 2½ × 3 = 7½ cups."},
    ],
    "Grade 6 Math — Expressions & Equations": [
        {"q": "Which expression represents 'eight less than twice a number n'?",
         "opts": ["8 − 2n", "2(8 − n)", "2n − 8", "2n + 8"],
         "ans": 2, "exp": "'Twice a number n' = 2n. 'Eight less than' means subtract 8 after: 2n − 8."},
        {"q": "Solve for x: 3x − 7 = 14",
         "opts": ["x = 2⅓", "x = 7", "x = 63", "x = −7"],
         "ans": 1, "exp": "Add 7 to both sides: 3x = 21. Divide by 3: x = 7."},
        {"q": "A plumber charges a $45 flat fee plus $30 per hour. Which equation gives total cost C for h hours?",
         "opts": ["C = 45h + 30", "C = 30h + 45", "C = 30 + 45h", "C = 75h"],
         "ans": 1, "exp": "Fixed cost = $45 (flat fee). Variable cost = $30 × h. Total: C = 30h + 45."},
        {"q": "Which value of x makes the inequality x − 4 > 9 true?",
         "opts": ["x = 10", "x = 12", "x = 13", "x = 14"],
         "ans": 3, "exp": "x − 4 > 9 → x > 13. So x = 14 is the only option greater than 13."},
        {"q": "Simplify: 4(2x + 3) − 5x",
         "opts": ["8x + 3", "3x + 12", "3x + 3", "8x + 12"],
         "ans": 1, "exp": "Distribute: 8x + 12. Subtract 5x: 3x + 12."},
    ],
    "Grade 6 Math — Geometry": [
        {"q": "A triangle has a base of 12 cm and a height of 9 cm. What is its area?",
         "opts": ["108 cm²", "54 cm²", "21 cm²", "42 cm²"],
         "ans": 1, "exp": "A = ½ × b × h = ½ × 12 × 9 = 54 cm²."},
        {"q": "A rectangular prism has length = 6 ft, width = 4 ft, and height = 5 ft. What is its volume?",
         "opts": ["120 ft³", "148 ft²", "74 ft³", "60 ft³"],
         "ans": 0, "exp": "V = l × w × h = 6 × 4 × 5 = 120 ft³."},
        {"q": "Point A is at (−3, 2) and Point B is at (4, 2). What is the distance between them?",
         "opts": ["1 unit", "5 units", "6 units", "7 units"],
         "ans": 3, "exp": "Same y-coordinate → horizontal distance = |4 − (−3)| = |7| = 7 units."},
        {"q": "What is the area of a trapezoid with bases of 8 in and 12 in, and a height of 5 in?",
         "opts": ["50 in²", "100 in²", "40 in²", "60 in²"],
         "ans": 0, "exp": "A = ½(b₁ + b₂)h = ½(8 + 12)(5) = ½(20)(5) = 50 in²."},
        {"q": "A point is plotted at (−4, −3). In which quadrant is it located?",
         "opts": ["Quadrant I", "Quadrant II", "Quadrant III", "Quadrant IV"],
         "ans": 2, "exp": "Both coordinates are negative → Quadrant III (−, −)."},
    ],
    "Grade 6 Math — Data Analysis": [
        {"q": "Ages: 11, 13, 12, 14, 12, 11, 15. What is the median?",
         "opts": ["11", "12", "13", "12.5"],
         "ans": 1, "exp": "Sorted: 11, 11, 12, 12, 13, 14, 15. Middle (4th) value = 12."},
        {"q": "Data: 2, 5, 7, 9, 11, 14, 18. What is the IQR?",
         "opts": ["16", "9", "7", "11"],
         "ans": 1, "exp": "Q1 = 5 (median of 2,5,7), Q3 = 14 (median of 11,14,18). IQR = 14 − 5 = 9."},
        {"q": "Scores: 72, 85, 91, 85, 78, 95, 85. What is the mode?",
         "opts": ["85", "84.4", "85.5", "78"],
         "ans": 0, "exp": "85 appears 3 times — more than any other value."},
        {"q": "A box plot has Q1=15, Median=22, Q3=30, Min=8, Max=45. What is the IQR?",
         "opts": ["37", "22", "15", "8"],
         "ans": 2, "exp": "IQR = Q3 − Q1 = 30 − 15 = 15."},
        {"q": "Which data display is BEST for showing the frequency of values in intervals?",
         "opts": ["Dot plot", "Stem-and-leaf", "Histogram", "Box plot"],
         "ans": 2, "exp": "Histograms group data into intervals and show how many fall in each — perfect for frequency by interval."},
    ],
    "Grade 6 ELA — Literary Devices": [
        {"q": "Which sentence uses a SIMILE?",
         "opts": ['"The classroom was a zoo."',
                  '"Her smile was sunshine."',
                  '"He ran like a cheetah through the halls."',
                  '"The hungry book devoured her attention."'],
         "ans": 2, "exp": "'Like a cheetah' uses 'like' to compare — that's a simile. The others are metaphors or personification."},
        {"q": "What literary device is used in: 'The thunder grumbled and the wind whispered warnings'?",
         "opts": ["Simile", "Personification", "Alliteration", "Hyperbole"],
         "ans": 1, "exp": "Thunder 'grumbling' and wind 'whispering' gives human actions to non-human things = personification."},
        {"q": "Which is an example of HYPERBOLE?",
         "opts": ['"The cat sat quietly."',
                  '"I am so tired I could sleep for a year."',
                  '"The stars looked like diamonds."',
                  '"She arrived early every morning."'],
         "ans": 1, "exp": "'Sleep for a year' is an extreme exaggeration for emphasis — that's hyperbole."},
        {"q": "'Buzz,' 'crash,' and 'sizzle' are all examples of:",
         "opts": ["Alliteration", "Personification", "Onomatopoeia", "Imagery"],
         "ans": 2, "exp": "These words imitate sounds — that's onomatopoeia."},
        {"q": "Which sentence contains alliteration?",
         "opts": ['"She sells seashells by the seashore."',
                  '"The moon is a silver coin."',
                  '"I have told you a thousand times!"',
                  '"The door creaked open slowly."'],
         "ans": 0, "exp": "Repeated 's' sound at the start of words = alliteration."},
    ],
    "Grade 6 ELA — Reading Comprehension": [
        {"q": "Which text structure signal words indicate CAUSE AND EFFECT?",
         "opts": ["First, next, then, finally",
                  "Because, therefore, as a result",
                  "Similarly, however, on the other hand",
                  "For example, specifically, such as"],
         "ans": 1, "exp": "'Because,' 'therefore,' and 'as a result' signal that one event caused another = cause and effect."},
        {"q": "An author's purpose to PERSUADE means:",
         "opts": ["The author wants to teach the reader facts",
                  "The author wants to entertain with a story",
                  "The author wants to convince the reader to agree with an opinion",
                  "The author wants to describe a process step by step"],
         "ans": 2, "exp": "Persuade = convince the reader to take a position or action (PIE: Persuade, Inform, Entertain)."},
        {"q": "Making an INFERENCE requires:",
         "opts": ["Only information directly stated in the text",
                  "Only the reader's personal opinion",
                  "Text evidence combined with prior knowledge",
                  "The author's stated conclusion"],
         "ans": 2, "exp": "Inference = reading between the lines: text clues + what you already know = logical conclusion."},
        {"q": "The THEME of a story is best described as:",
         "opts": ["A one-word topic like 'friendship'",
                  "A summary of all the plot events",
                  "A life lesson or message expressed as a complete sentence",
                  "The main character's goal in the story"],
         "ans": 2, "exp": "Theme is a universal message (complete sentence). Topic = friendship. Theme = 'True friendship requires sacrifice.'"},
        {"q": "In a text using COMPARE AND CONTRAST structure, which signal word would you expect?",
         "opts": ["Therefore", "As a result", "However", "Finally"],
         "ans": 2, "exp": "'However' signals a contrast. Compare/contrast texts highlight similarities AND differences between subjects."},
    ],
}

# ── Monthly study plan aligned with TEKS pacing ──────────────────────────────

STUDY_PLAN_G6 = [
    {"month": "Aug 12–Aug 31", "label": "Foundation",
     "math": ["Review integers and number classification", "Absolute value basics", "Number line activities"],
     "ela":  ["Story elements review (plot, character, theme)", "Author's purpose practice", "Reading stamina building"],
     "tip":  "Establish daily study habits early — 20 min Math + 20 min reading daily pays off by April."},
    {"month": "September", "label": "Number Operations + Narrative",
     "math": ["Integer operations (all 4)", "Fraction multiplication & division", "Decimal operations", "PEMDAS"],
     "ela":  ["Point of view identification", "Personal narrative writing", "Simile, metaphor, imagery"],
     "tip":  "Khan Academy Grade 6 Math TX — complete the Number & Operations unit this month."},
    {"month": "October", "label": "Ratios + Informational Reading",
     "math": ["Ratios and notation", "Unit rates", "Equivalent ratios and tables", "Scale drawings"],
     "ela":  ["Main idea and supporting details", "Text structures (especially cause/effect)", "Informational writing"],
     "tip":  "Fall Break Oct 12–16. Sprint before break, then light review during."},
    {"month": "November", "label": "Percent + Research Writing",
     "math": ["Converting between fractions/decimals/percents", "Tax, tip, discount", "Simple interest intro"],
     "ela":  ["Research skills: credible sources, note-taking", "MLA citations", "Informational essay draft"],
     "tip":  "Take the first Effortless Math full practice test — see where you are. Thanksgiving week: ELA reading only."},
    {"month": "December", "label": "Expressions + Argumentative",
     "math": ["Writing and evaluating expressions", "Independent vs. dependent variables", "Input/output tables"],
     "ela":  ["Claims and evidence in argument", "Counterclaims", "Argumentative essay intro"],
     "tip":  "Winter Break Dec 21: take a real break, then 30 min daily review Jan 1–3."},
    {"month": "January", "label": "Equations & Inequalities + Poetry",
     "math": ["One-step equations (all operations)", "Solving and checking equations", "Graphing inequalities"],
     "ela":  ["Figurative language deep-dive", "Poetry analysis (tone, mood, structure)", "Drama elements"],
     "tip":  "MLK Day Jan 19. Do the TEA Grade 6 interactive practice test (math) this month for the first time."},
    {"month": "February", "label": "Geometry + Comprehension Strategies",
     "math": ["Area of triangles and quadrilaterals", "Composite figures", "Surface area and nets"],
     "ela":  ["Inference from text evidence", "Context clues for vocabulary", "Cross-text comparison"],
     "tip":  "Presidents Day Feb 15. Try the TEA Grade 6 RLA interactive test. Review literary device flashcards daily."},
    {"month": "March", "label": "Volume + Argumentative Writing Polish",
     "math": ["Volume of rectangular prisms", "Coordinate plane (all 4 quadrants)", "Distance on coordinate plane"],
     "ela":  ["Full argumentative essay (draft → revise → edit)", "Peer review strategies", "Grammar: complex sentences"],
     "tip":  "Spring Break Mar 15–19. Before break: take a full timed mini-test. After break: error analysis only."},
    {"month": "April", "label": "★ STAAR Prep Sprint",
     "math": ["Data analysis: mean, median, IQR, box plots, histograms", "Personal financial literacy", "FULL released tests daily"],
     "ela":  ["STAAR format practice: literary + informational paired passages", "Extended response practice", "Grammar speed review"],
     "tip":  "★ STAAR Reading ~Apr 6  |  ★ STAAR Math ~Apr 8\nFinal week: sleep 9 hrs, eat breakfast, review formulas only."},
    {"month": "May", "label": "Post-STAAR + Grade 7 Preview",
     "math": ["Financial literacy projects", "Spiral review of weakest strands", "Grade 7 preview: proportional relationships"],
     "ela":  ["Independent reading choice book", "Oral presentation skills", "Portfolio reflection"],
     "tip":  "Last Day May 28. Celebrate STAAR completion! Keep reading over summer."},
]
